"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Created: ${create_date}

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | typing.Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | typing.Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Apply this migration."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Undo this migration."""
    ${downgrades if downgrades else "pass"}
