"""The conventions ruff cannot check, checked — `#1082`.

**Ruff is a linter here and never a formatter**, deliberately: ``ruff format`` would strip the
space in ``def foo (x)`` and re-indent with spaces, both of which the house style requires the
other way round. So the three rules most likely to be broken by somebody reaching for a
formatter — tabs, that space, and a docstring on every function — are checked by nothing at
all, and the only reader they have ever had is a person looking.

A cold review swept these mechanically on 2026-08-21 and reported **seven** functions without a
docstring, from the commit range it was given. Over the whole tree there were **twenty-five**.
That gap is the argument for a guard rather than a sweep: a sweep is as good as its scope and
nobody re-runs it.

**Migrations are out**, as everywhere else here: they are generated by Alembic and follow its
conventions rather than ours, which ``CONTRIBUTING.md`` records.
"""

import ast
import pathlib
import re
import typing

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent

#: Where the house style applies. Everything tracked and written by hand.
CHECKED = ("src", "tests", "scripts")


def _files () -> list[pathlib.Path]:
	"""Return every Python file the house style governs."""

	return [
		path
		for directory in CHECKED
		for path in sorted((ROOT / directory).rglob("*.py"))
		if "versions" not in path.parts
	]


def _functions (path: pathlib.Path) -> typing.Iterator[ast.FunctionDef | ast.AsyncFunctionDef]:
	"""Yield every function in one file, nested ones included."""

	for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
		if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
			yield node


def test_the_style_scan_reaches_the_whole_tree () -> None:
	"""A floor, because every assertion below passes over an empty walk.

	`SR#405`'s rule and this repository's most-repeated lesson: a scanner that reads nothing
	reports a clean tree. So a count, a file that must be in it, and a function that must be
	found inside that file.
	"""

	files = _files()

	assert len(files) > 150, f"only {len(files)} files reached; the tree is larger than that"
	assert any(path.name == "readiness.py" for path in files)

	named = {node.name for node in _functions(ROOT / "src" / "subroutine" / "domain" / "readiness.py")}

	assert "ready" in named, f"the function walk found {sorted(named)}"


def test_every_function_has_a_docstring () -> None:
	"""The house style's word is *mandatory*, and nested closures are functions too.

	**Nested ones are where they go missing**, which is what the review's seven were: a helper
	inside a test reads as scaffolding rather than as code somebody will have to understand. It
	is read more often than most of what surrounds it, because it is what the assertion means.
	"""

	missing = [
		f"{path.relative_to(ROOT)}:{node.lineno} {node.name}"
		for path in _files()
		for node in _functions(path)
		if ast.get_docstring(node) is None
	]

	assert not missing, "functions with no docstring:\n" + "\n".join(missing)


def test_a_definition_carries_the_space_a_call_does_not () -> None:
	"""``def foo (x)`` and ``foo(x)`` — the space is what tells them apart at a glance.

	Scanned off the source rather than off the AST, because what this is about is the *text*: an
	AST cannot see whitespace, and whitespace is the whole rule. A formatter run by accident is
	the way it breaks, and it would break every definition at once.
	"""

	pattern = re.compile(r"^\s*(?:async\s+)?def\s+\w+\(")
	wrong = [
		f"{path.relative_to(ROOT)}:{number} {line.strip()[:60]}"
		for path in _files()
		for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1)
		if pattern.match(line)
	]

	assert not wrong, (
		"a definition with no space before its parenthesis:\n" + "\n".join(wrong)
	)


def test_nothing_is_indented_with_spaces () -> None:
	"""Tabs only, and strictly.

	**Continuation lines and prose are not indentation**, which is why this reads the leading
	whitespace of lines that begin a statement rather than every line: a wrapped argument list
	aligns with spaces after its tab, and a docstring may hold an indented code block. What is
	forbidden is a line whose *indent itself* is made of spaces.
	"""

	offenders = []

	for path in _files():
		text = path.read_text(encoding="utf-8")
		lines = text.splitlines()
		# Which lines sit inside a string literal, and are therefore prose rather than code.
		prose: set[int] = set()

		for node in ast.walk(ast.parse(text)):
			if (
				isinstance(node, ast.Constant)
				and isinstance(node.value, str)
				and node.end_lineno is not None
			):
				prose.update(range(node.lineno, node.end_lineno + 1))

		for number, line in enumerate(lines, start=1):
			if number in prose or not line.strip():
				continue

			if line.startswith(" "):
				offenders.append(f"{path.relative_to(ROOT)}:{number} {line.strip()[:60]}")

	assert not offenders, "indented with spaces:\n" + "\n".join(offenders)


@pytest.mark.parametrize(
	("rule", "planted"),
	[
		("docstring", "def helper ():\n\treturn 1\n"),
		("definition space", 'def helper():\n\t"""Do a thing."""\n\n\treturn 1\n'),
		("tabs", 'def helper ():\n    """Do a thing."""\n\n    return 1\n'),
	],
)
def test_each_rule_catches_its_own_defect (
	tmp_path: pathlib.Path, rule: str, planted: str
) -> None:
	"""Every check driven against a file built to break it, and only it.

	`SR#405`: a guard tested by a copy of its own rule confirms the copy. These are the real
	scanners, handed a real file — which is what says the assertion above is doing something,
	and what stops a future tightening quietly stopping.
	"""

	path = tmp_path / "planted.py"
	path.write_text(planted, encoding="utf-8")

	broke = []

	if any(ast.get_docstring(node) is None for node in _functions(path)):
		broke.append("docstring")

	if re.compile(r"^\s*(?:async\s+)?def\s+\w+\(", re.M).search(planted):
		broke.append("definition space")

	prose: set[int] = set()

	for node in ast.walk(ast.parse(planted)):
		if (
			isinstance(node, ast.Constant)
			and isinstance(node.value, str)
			and node.end_lineno is not None
		):
			prose.update(range(node.lineno, node.end_lineno + 1))

	if any(
		line.startswith(" ")
		for number, line in enumerate(planted.splitlines(), start=1)
		if number not in prose and line.strip()
	):
		broke.append("tabs")

	assert broke == [rule], f"a file planted to break {rule!r} was read as breaking {broke}"
