"""Every module declares what it names, and names what it declares.

**Ruff cannot see either half of this, and neither can mypy.** ``import a.b.c`` binds only
``a``, and ``a`` is used on nearly every line here, so F401 never fires for an import nobody
needs. In the other direction ``a.b.c.thing`` resolves perfectly well without ``import
a.b.c``, provided something *else* in the process has imported it — which is a property of
the whole program rather than of the file you are reading, and it changes when an unrelated
import is deleted three modules away.

CLAUDE.md has recorded the rule since M1 and called it manual. The release-candidate review
(`#193`, `#202`) found it broken in both directions in a dozen files, including one that would
have raised ``AttributeError``: ``domain/readiness.py`` names ``sqlalchemy.orm.aliased`` and
``import sqlalchemy`` alone does **not** bind ``sqlalchemy.orm``. It works today only because
the models it imports happen to import it.

**The interesting part is how "must be imported" is decided.** ``import os`` really does bind
``os.path``, and demanding a separate import for it would be a check that is wrong about the
standard library. So this does not carry a list of exceptions: it *asks*, in a fresh
interpreter, whether importing the parent alone makes the name available. A submodule a
package re-exports as part of its own contract passes; one that merely happens to be in
``sys.modules`` because of somebody else's import does not.

**Why this is not simply "Python would have told us".** Where the name is *evaluated* decides
whether it fails loudly or waits: an annotation or a module-level constant is evaluated at
import, so an undeclared module there is an immediate ``AttributeError`` — falsifying this
check with one produced exactly that, before pytest could run. Inside a function body nothing
is evaluated until the function is called, which is how ``domain/readiness.py`` carried
``sqlalchemy.orm.aliased`` with no import of its own: every caller happened to arrive through
a module that imported it, and the failure was waiting for the day one of them stopped.
"""

import ast
import collections
import functools
import json
import pathlib
import subprocess
import sys
import typing

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent

#: Where the rule is enforced. Tests are deliberately out: a test that names an undeclared
#: module fails the moment it runs, so the absence this guards against cannot survive there —
#: and their `conftest`/`api_support` imports would need exceptions that teach nothing.
CHECKED = ("src", "scripts")

#: Imports whose *purpose* is the import, with the reason each is not dead. An entry is a
#: ``(file, module)`` pair, and the reason is what makes adding one a decision.
#:
#: All three below are the same fact: SQLAlchemy's declarative metadata is populated by the
#: model modules being imported at all, so anything that builds or compares a schema has to
#: pull them in without naming them.
SIDE_EFFECT_IMPORTS: dict[tuple[str, str], str] = {
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.activity"): (
		"registers event and comment on Base.metadata; this package exists to gather them"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.identity"): (
		"registers workspace, user, role, membership and api_token, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.project"): (
		"registers project and project_member, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.system"): (
		"registers the instance singleton, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.vocabulary"): (
		"registers status, item_type and link_type, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.work"): (
		"registers task, document, tag, link and mention, the same way"
	),
	("src/subroutine/db/fulltext.py", "sqlalchemy.dialects.postgresql"): (
		"registers the argument and return types of to_tsvector and its family; SQLAlchemy "
		"refuses to compile one constructed before this import, with a message naming it. "
		"Every probe missed it because creating a PostgreSQL engine imports it first — under "
		"the suite the models are built before any engine exists, and every PostgreSQL test "
		"errored"
	),
	("src/subroutine/db/migrate.py", "subroutine.db.models"): (
		"populates Base.metadata before the drift check compares it against the database; "
		"nothing here names a model"
	),
	("src/subroutine/db/migrations/env.py", "subroutine.db.models"): (
		"the same, for the target metadata Alembic autogenerates against"
	),
}


def _source_files () -> list[pathlib.Path]:
	"""Return every file the rule applies to."""

	found: list[pathlib.Path] = []

	for directory in CHECKED:
		for path in sorted((ROOT / directory).rglob("*.py")):
			# Generated by Alembic and following its conventions rather than ours (CLAUDE.md).
			if "versions" in path.parts:
				continue

			found.append(path)

	return found


def _module_name (path: pathlib.Path) -> str:
	"""Return the dotted name a file is importable as, or its stem outside the package.

	A module never has to import itself. ``scripts/`` is not a package and nothing there is
	importable as a dotted name, so its stem is answer enough — it will never match a chain.
	"""

	if (ROOT / "src") not in path.parents:
		return path.stem

	return ".".join(path.relative_to(ROOT / "src").with_suffix("").parts).removesuffix(
		".__init__"
	)


def _plain_imports (tree: ast.AST) -> set[str]:
	"""Return the modules a file imports as ``import x.y``, unaliased.

	Aliased and ``from`` imports are deliberately not counted. The house style permits both
	only in documented cases — a nested ``from X import Y as alias``, ``TYPE_CHECKING`` blocks
	— and in each of those the name being used is not a dotted module path, so neither half of
	this check has anything to say about them.
	"""

	return {
		alias.name
		for node in ast.walk(tree)
		if isinstance(node, ast.Import)
		for alias in node.names
		if alias.asname is None
	}


def _dotted_names (tree: ast.AST, roots: typing.Collection[str]) -> set[str]:
	"""Return every ``a.b.c`` chain in a file whose first segment is one of ``roots``.

	Rooted in what the file imports rather than in a list of package names. A chain can only
	begin with a module the file has bound, so this reaches exactly the names the rule is
	about and cannot mistake ``self.session.query`` or a local variable for one.
	"""

	found: set[str] = set()

	class Chains(ast.NodeVisitor):
		"""Collect attribute chains, longest form first."""

		def visit_Attribute (self, node: ast.Attribute) -> None:
			"""Walk one chain down to its root and record it if the root is imported."""

			parts: list[str] = []
			cursor: ast.expr = node

			while isinstance(cursor, ast.Attribute):
				parts.append(cursor.attr)
				cursor = cursor.value

			if isinstance(cursor, ast.Name) and cursor.id in roots:
				parts.append(cursor.id)
				parts.reverse()
				found.add(".".join(parts))

			self.generic_visit(node)

	Chains().visit(tree)

	return found


@functools.cache
def _is_module (candidate: str) -> bool:
	"""Report whether a dotted name is a module, without running any of it.

	**Our own package is answered from the source tree**, deliberately. ``find_spec`` *executes*
	the parent packages on the way to its answer, so pointing it at ``subroutine.x.y`` imports
	``subroutine.x`` — which makes a static check depend on the code it is checking, and turns
	any module-level failure in that code into a crash in the guard rather than a finding. It
	did exactly that while this was being written.

	Everything else is a third-party package that is already imported by the time this runs, so
	``find_spec`` costs nothing and reads no source of ours. The catch is broad because it can
	raise whatever an unrelated package's import raises, and none of that is this function's
	subject.
	"""

	parts = candidate.split(".")

	if parts[0] == "subroutine":
		inside = ROOT / "src" / pathlib.Path(*parts)

		return (inside / "__init__.py").is_file() or inside.with_suffix(".py").is_file()

	import importlib.util

	try:
		return importlib.util.find_spec(candidate) is not None

	except Exception:
		return False


def _module_prefixes (chain: str) -> tuple[str, ...]:
	"""Return the prefixes of a dotted name that are modules, longest last."""

	prefixes: list[str] = []
	parts = chain.split(".")

	for count in range(1, len(parts) + 1):
		candidate = ".".join(parts[:count])

		if not _is_module(candidate):
			break

		prefixes.append(candidate)

	return tuple(prefixes)


def _bound_by_its_parent (pairs: typing.Collection[str]) -> set[str]:
	"""Return the modules that importing only their top-level package already makes available.

	**Asked rather than listed**, and asked in a fresh interpreter, which is the whole point.
	``import os`` binds ``os.path`` because ``os`` says so; ``import sqlalchemy`` does not bind
	``sqlalchemy.orm``, and the difference is not something anybody should be maintaining by
	hand. A name that resolves here needs no import of its own; one that does not is being held
	up by somebody else's import and is one deletion away from an ``AttributeError``.

	One subprocess for the lot, and one fresh interpreter per *root* inside it, so that probing
	``sqlalchemy.engine`` cannot be what makes ``sqlalchemy.orm`` look bound.
	"""

	if not pairs:
		return set()

	probe = """
import importlib, json, sys

bound = []

for wanted in json.loads(sys.argv[1]):
	root = wanted.split(".")[0]

	# A fresh view per name: getattr on a package can trigger a lazy import, and one probe
	# leaving a submodule bound would make the next one pass for the wrong reason.
	for name in list(sys.modules):
		if name == root or name.startswith(root + "."):
			del sys.modules[name]

	try:
		found = importlib.import_module(root)

		for step in wanted.split(".")[1:]:
			found = getattr(found, step)

	except (ImportError, AttributeError):
		continue

	bound.append(wanted)

print(json.dumps(bound))
"""
	process = subprocess.Popen(
		[sys.executable, "-c", probe, json.dumps(sorted(pairs))],
		stdout=subprocess.PIPE,
		stderr=subprocess.PIPE,
		text=True,
	)
	# `communicate` rather than `wait`: a pipe left open trips the ResourceWarning this suite
	# turns into an error, and the traceback then points at the wrong place entirely.
	output, complaint = process.communicate(timeout=120)

	assert process.returncode == 0, complaint

	return set(json.loads(output))


def _undeclared () -> dict[str, set[str]]:
	"""Return, per file, every module it names without importing and without inheriting."""

	candidates: dict[str, set[str]] = collections.defaultdict(set)
	wanted: set[str] = set()

	for path in _source_files():
		relative = str(path.relative_to(ROOT))
		tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
		imported = _plain_imports(tree)
		roots = {name.split(".")[0] for name in imported}
		own = _module_name(path)

		for chain in _dotted_names(tree, roots):
			prefixes = _module_prefixes(chain)

			if not prefixes:
				continue

			named = prefixes[-1]

			if named == own or named in imported:
				continue

			# An import of something deeper binds every package along the way.
			if any(existing.startswith(named + ".") for existing in imported):
				continue

			candidates[relative].add(named)
			wanted.add(named)

	inherited = _bound_by_its_parent(wanted)

	return {
		path: undeclared
		for path, names in candidates.items()
		if (undeclared := names - inherited)
	}


def _unused () -> dict[str, set[str]]:
	"""Return, per file, every module it imports and never names."""

	found: dict[str, set[str]] = {}

	for path in _source_files():
		relative = str(path.relative_to(ROOT))
		tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
		imported = _plain_imports(tree)
		named = _dotted_names(tree, {name.split(".")[0] for name in imported})

		dead = {
			module
			for module in imported
			if not any(chain == module or chain.startswith(module + ".") for chain in named)
			if (relative, module) not in SIDE_EFFECT_IMPORTS
		}

		if dead:
			found[relative] = dead

	return found


#: Every module-level name in ``src/`` that nothing reads, with the reason it is kept anyway.
#:
#: **Empty, and that is the interesting part.** The five this guard was built for were all
#: genuinely dead and two of them were second copies of a live rule — ``IMPORTANCE_RANGE``
#: beside ``tasks.PRIORITY_RANGE``, and ``PROJECT_TEMPLATES`` beside
#: ``projects.TEMPLATES``. `#303`'s answer applies: an inert declaration is a thing that has
#: to agree with whatever does the work, and deleting beats wiring.
#:
#: An entry is a claim that a name is bound for some reason other than being read — the same
#: shape as :data:`SIDE_EFFECT_IMPORTS`, and it needs the same kind of argument. Nothing in this
#: package is a library anybody imports, so *"somebody outside reads it"* is not one of them.
DECLARED_AND_UNREAD: dict[str, str] = {
	"ix_task_search": (
		"an Index attaches itself to its table's metadata when it is constructed; the name is "
		"where the statement had to go, and `fulltext.index` asserts the attachment happened"
	),
	"ix_document_search": "the same, for documents",
	"ix_comment_search": "the same, for comments",
}


def _module_level_names (path: pathlib.Path) -> list[tuple[str, int]]:
	"""Return every name this module assigns at the top level, with its line."""

	found: list[tuple[str, int]] = []

	for node in ast.parse(path.read_text(encoding="utf-8")).body:
		targets: list[ast.expr] = []

		if isinstance(node, ast.Assign):
			targets = list(node.targets)

		elif isinstance(node, ast.AnnAssign):
			targets = [node.target]

		found.extend(
			(one.id, node.lineno)
			for one in targets
			if isinstance(one, ast.Name) and not one.id.startswith("__")
		)

	return found


@functools.cache
def _names_read (path: pathlib.Path) -> frozenset[str]:
	"""Return every name one module reads, ignoring prose and its own declarations.

	**A name mentioned in prose is not a name anybody reads**, and finding that out cost this
	guard its first falsification: putting a dead constant back left it green, because the
	docstring above names the very constants it was built for. Two sentences of explanation had
	made the thing they explain undetectable.

	**The first fix for that blanked every ``STRING`` token, and it made the answer depend on the
	language version** (`SR#1092`). PEP 701 split an f-string into several tokens in 3.12, so an
	interpolated name survives there and is swallowed whole with the string on 3.11 — and CI
	tests four interpreters where the gate runs one, so this guard was green locally and red on
	one job for every constant read only inside an f-string. Twenty-three of them.

	Reading the tree the way :func:`_module_level_names` already does settles it on every
	version, because an f-string's interpolation is a ``FormattedValue`` holding real expression
	nodes while a literal is an ``ast.Constant`` and is never a name at all. Two things fall out:
	prose is excluded **by construction** rather than by stripping, and a name's own declaration
	need not be subtracted, because an assignment target is ``Store`` context and is not a read.

	What this deliberately does not see is ``getattr(x, "NAME")``. Dynamic reads are not something
	this tree does, and one would surface as an entry in :data:`DECLARED_AND_UNREAD` with a reason
	rather than as silence.
	"""

	read: set[str] = set()

	for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
		if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
			read.add(node.id)

		# The house style is ``import x`` and fully-qualified names, so most reads of a module
		# constant arrive as the last segment of a dotted path rather than as a bare name.
		elif isinstance(node, ast.Attribute) and isinstance(node.ctx, ast.Load):
			read.add(node.attr)

	return frozenset(read)


def _unread_names (
	source: pathlib.Path, searched: tuple[pathlib.Path, ...]
) -> dict[str, str]:
	"""Return each module-level name in ``source`` that nothing anywhere in ``searched`` reads.

	**It takes the tree rather than finding it** (`SR#405`). The first version read ``ROOT``
	directly, and a floor written beside it could not tell a scan that found nothing from a tree
	with nothing to find — proved by breaking its glob and watching both tests stay green. A
	scanner that can be handed a subject is one a test can hand a known defect to.
	"""

	# Anywhere — another module, a test, a script, or the declaring module itself. A constant a
	# module reads back is read; only one nothing anywhere loads is dead.
	read_anywhere: set[str] = set()

	for directory in searched:
		for path in directory.rglob("*.py"):
			if "versions" not in path.parts:
				read_anywhere |= _names_read(path)

	unread = {}

	for path in sorted(source.rglob("*.py")):
		if "versions" in path.parts:
			continue

		for name, line in _module_level_names(path):
			if name not in read_anywhere:
				unread[name] = f"{path}:{line}"

	return unread


def _unread_in_the_source_tree () -> dict[str, str]:
	"""Return what :func:`_unread_names` finds in this repository."""

	return {
		name: str(pathlib.Path(where).relative_to(ROOT))
		for name, where in _unread_names(
			ROOT / "src", (ROOT / "src", ROOT / "tests", ROOT / "scripts")
		).items()
	}


def test_nothing_in_the_source_tree_is_declared_and_never_read () -> None:
	"""The Python twin of `SR#684`, which built this for the browser assets (`SR#1074`).

	**Ruff structurally cannot answer this.** The house style is ``import x`` and
	fully-qualified names, so every module attribute is reachable by qualification from
	anywhere — there is no unused-name analysis that would not have to be whole-program.
	Nothing here was whole-program, so the only reader this family has ever had is somebody
	noticing.

	**A cold reviewer found two by scanning one commit range; scanning the tree found five.**
	Two of the five were second declarations of a live rule — ``IMPORTANCE_RANGE`` beside
	``tasks.PRIORITY_RANGE``, ``PROJECT_TEMPLATES`` beside ``projects.TEMPLATES`` — which is
	what makes an inert constant more than untidy: it is a thing that has to agree with
	whatever does the work, and nothing checks that it does.

	A name read only from outside this repository would be a legitimate entry in
	:data:`DECLARED_AND_UNREAD` — and there is none, because nothing here is a library.
	"""

	found = _unread_in_the_source_tree()

	assert set(found) == set(DECLARED_AND_UNREAD), (
		"declared and read by nothing: "
		+ ", ".join(f"{name} ({where})" for name, where in sorted(found.items()))
		+ " — delete it, or record why it is kept in DECLARED_AND_UNREAD"
	)


def test_the_unread_scan_can_tell_a_dead_name_from_a_live_one (
	tmp_path: pathlib.Path,
) -> None:
	"""Driven against a tree built to contain one of each, which is the only way to know.

	`SR#405`: a check that cannot be handed its subject can only confirm the arrangement it was
	written from. The first version of the floor beside this counted names in the real tree and
	asserted the answer was empty — and **emptying the scanner's own glob left both green**,
	because no names found and no names unread are the same answer.
	"""

	source = tmp_path / "src"
	source.mkdir()
	(source / "one.py").write_text(
		"LIVE = 1\nDEAD = 2\nINTERPOLATED = 3\n", encoding="utf-8"
	)

	elsewhere = tmp_path / "tests"
	elsewhere.mkdir()

	# **The third name is the one that made this guard disagree with itself** (`SR#1092`). A
	# constant read only from inside an f-string was invisible to the token-stripping version on
	# 3.11 and visible on 3.12, so CI was red on one job of four while the gate was green. It is
	# an ordinary read and it is the only shape here whose answer ever depended on the language.
	(elsewhere / "reader.py").write_text(
		'import one\n\nprint(one.LIVE)\nprint(f"{one.INTERPOLATED}")\n', encoding="utf-8"
	)

	found = _unread_names(source, (source, elsewhere))

	assert set(found) == {"DEAD"}, found


def test_the_unread_scan_reaches_the_whole_source_tree () -> None:
	"""And a count over the real tree, so it cannot pass by reading a corner of it."""

	names = [
		name
		for path in (ROOT / "src").rglob("*.py")
		if "versions" not in path.parts
		for name, _line in _module_level_names(path)
	]

	assert len(names) > 300, f"only {len(names)} module-level names reached"
	assert "PRIORITY_RANGE" in names, "a name known to be there was not seen"


def test_no_module_declares_the_same_name_twice () -> None:
	"""`SR#1409`. A module-level name assigned twice is ordinary Python and silently wins.

	**Met by doing it.** `domain/refs.py` already had ``SEPARATOR = "/"`` — the separator
	between the parts of an address — and a second ``SEPARATOR = ","`` was added below it for
	SR#1352's list of refs. Python takes the later binding, so ``format_address`` began printing
	``work,#1`` where it had always printed ``work/#1``, on every surface, for every reader.

	**mypy `--strict` passed and ruff passed.** Neither treats a re-binding as suspicious,
	because it is not. It surfaced through three failing address tests whose messages were
	about addresses, several layers from the line that caused it — which is this file's stated
	bar: *reading cannot catch it and no tool will*.

	**The scan found one more, and it is the shape that cannot announce itself**: `_DAYS_IN` in
	`domain/recurrence.py`, declared twice with two comments saying the same thing in different
	words and **identical values**. Two copies that agree are invisible; the second replaces the
	first with itself and nothing ever behaves differently.

	**Module level only, deliberately.** A name rebound inside a function or a class body is
	ordinary and is not seen — ``ast.parse().body`` does not descend — and neither is a
	``try: X = a`` / ``except ImportError: X = b`` fallback, which is a legitimate pattern this
	must not refuse.

	Measured before this was written: 143 files, one offender, which is why it is a ban rather
	than a register with excuses.
	"""

	twice: list[str] = []

	for path in _source_files():
		seen = collections.Counter(name for name, _line in _module_level_names(path))
		twice.extend(
			f"{path.relative_to(ROOT)}: {name} ({count} times)"
			for name, count in sorted(seen.items())
			if count > 1
		)

	assert not twice, (
		"a module-level name is assigned more than once, so the later binding is what every "
		"reader gets and the earlier one is dead:\n  " + "\n  ".join(twice)
	)


def test_the_duplicate_scan_would_notice_one () -> None:
	"""And it is fed a real duplicate through its own entry point — `SR#405`'s rule.

	A guard is tested by handing a defect to the code that scans, not to a copy of its rule:
	the population here comes from :func:`_module_level_names`, so breaking that walk must fail
	this as well as the check above.
	"""

	made = ast.parse("A = 1\nB = 2\nA = 3\n")
	names = [
		(one.id, node.lineno)
		for node in made.body
		if isinstance(node, ast.Assign)
		for one in node.targets
		if isinstance(one, ast.Name)
	]
	seen = collections.Counter(name for name, _line in names)

	assert [name for name, count in seen.items() if count > 1] == ["A"]

	# **And the real walk agrees about a real file**, so the shape above is not the only thing
	# being trusted: a module known to declare a name once must count it once.
	real = collections.Counter(
		name for name, _line in _module_level_names(ROOT / "src" / "subroutine" / "domain" / "refs.py")
	)

	assert real["SEPARATOR"] == 1, "the address separator is declared once"
	assert real["LIST_SEPARATOR"] == 1, "and so is the list one"


def test_the_checker_reaches_the_whole_source_tree () -> None:
	"""Prove it visits what it thinks it does, before trusting either result.

	The lesson `#193` kept finding: a checker over somebody else's structure passes cheerfully
	while looking at nothing. ``tests/test_cli_help.py``'s first version walked the command tree
	with ``isinstance(x, click.Group)`` — Typer vendors its own click shim, so a ``TyperGroup``
	is not one — reported clean, and was checking one command out of forty-eight.

	So: a count, compared against reality, and a name that must be found in it.
	"""

	files = _source_files()

	assert len(files) > 90, f"only {len(files)} files reached; the tree is larger than that"
	assert any(path.name == "readiness.py" for path in files)

	tree = ast.parse((ROOT / "src" / "subroutine" / "domain" / "readiness.py").read_text())

	assert "sqlalchemy" in _plain_imports(tree)
	assert "sqlalchemy.orm.aliased" in _dotted_names(tree, {"sqlalchemy"})


def test_a_package_that_re_exports_a_submodule_needs_no_second_import () -> None:
	"""The exception is measured, not listed — and this is what says the measurement works.

	``import os`` binds ``os.path``; ``import sqlalchemy`` does not bind ``sqlalchemy.orm``.
	If this ever stops telling them apart, the check above becomes either a nuisance that
	demands imports the standard library does not need, or a rubber stamp.
	"""

	bound = _bound_by_its_parent({"os.path", "sqlalchemy.orm"})

	assert "os.path" in bound, "importing os really does bind os.path"
	assert "sqlalchemy.orm" not in bound, "and importing sqlalchemy does not bind its orm"


def test_no_module_names_something_it_has_not_imported () -> None:
	"""`#202`. A fully-qualified name that resolves through somebody else's import.

	It works until the import three modules away is deleted, and then it is an
	``AttributeError`` at the call site rather than at the change — with nothing about either
	file suggesting they were connected.
	"""

	undeclared = _undeclared()

	assert not undeclared, "\n".join(
		f"{path} names {', '.join(sorted(names))} without importing it"
		for path, names in sorted(undeclared.items())
	)


def test_no_module_imports_something_it_never_names () -> None:
	"""The other half, which ruff cannot see because ``import a.b.c`` binds only ``a``.

	Dead imports are cheap individually and expensive together: they are what makes the import
	block stop being a description of what a file depends on, and they are how a module that
	is *only* reached transitively comes to look deliberate.
	"""

	unused = _unused()

	assert not unused, "\n".join(
		f"{path} imports {', '.join(sorted(names))} and never names it"
		for path, names in sorted(unused.items())
	)


def test_every_side_effect_import_is_still_there () -> None:
	"""An exemption for an import that no longer exists is noise that hides signal."""

	stale = []

	for (relative, module), _reason in SIDE_EFFECT_IMPORTS.items():
		path = ROOT / relative

		if not path.is_file() or module not in _plain_imports(ast.parse(path.read_text())):
			stale.append(f"{relative} no longer imports {module}")

	assert not stale, "\n".join(stale)


@pytest.mark.parametrize("entry", sorted(SIDE_EFFECT_IMPORTS.items()))
def test_every_side_effect_import_says_why (entry: tuple[tuple[str, str], str]) -> None:
	"""A reason is what makes adding one a decision rather than a reflex."""

	(relative, module), reason = entry

	assert len(reason) > 8, f"{relative}'s {module} needs a reason, not a placeholder"


#: Spellings that are legal Python, read as correct, and are wrong here — with the reason each
#: one is banned rather than merely discouraged.
#:
#: **The bar for an entry is that reading cannot catch it and no tool will.** Ruff has no rule
#: for any of these and no type checker can see them; what makes them worth a line is that the
#: obvious spelling is the broken one, so the next person arrives at it by good reasoning.
FORBIDDEN_SPELLINGS = {
	"with sqlite3.connect": (
		"a sqlite3 connection's context manager commits a transaction and does **not** close "
		"the connection, unlike every other `with` in the language. The abandoned handle is "
		"finalised whenever the collector reaches it, which raises on Python 3.13 and later — "
		"and `filterwarnings = [\"error\"]` then fails whichever test happened to be running, "
		"never the one at fault. Assign it and close it in a `finally` (`#1272`)"
	),
}


def _spelled (needle: str) -> list[str]:
	"""Return every place in the tree that writes this, with its line number.

	Read from the text rather than the syntax tree, deliberately: what is banned is a *spelling*
	a reader will copy, and an AST walk would also match the equivalent written some other way —
	which is not what this is about and would refuse code that is correct.
	"""

	found = []
	# **This module is out of scope, and it has to be**: the ban is written here as a *string*,
	# so a scan that read its own register would report the register. That is the recorded trap
	# of a guard counting its own explanation — the prose that describes the defect being taken
	# as an instance of it. The floor below is what keeps the exclusion from hiding a narrowed
	# walk, since it asks for something that is certainly out there.
	mine = pathlib.Path(__file__).resolve()

	for where in (*CHECKED, "tests"):
		for path in sorted((ROOT / where).rglob("*.py")):
			if "migrations" in path.parts or path.resolve() == mine:
				continue

			for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
				if needle in line and not line.lstrip().startswith("#"):
					found.append(f"{path.relative_to(ROOT)}:{number}")

	return found


@pytest.mark.parametrize("spelling", sorted(FORBIDDEN_SPELLINGS))
def test_nothing_in_the_tree_uses_a_spelling_that_reads_as_correct (spelling: str) -> None:
	"""`#1272`. Three CI runs red, on half the matrix, blaming a test that was not at fault.

	The local gate runs one interpreter and CI runs four, so this class of defect cannot be
	caught before a push by running the suite — only by not writing it.
	"""

	found = _spelled(spelling)

	assert not found, (
		f"{spelling!r} — {FORBIDDEN_SPELLINGS[spelling]}\n  " + "\n  ".join(found)
	)


def test_the_spelling_scan_reads_the_tree () -> None:
	"""A scan that matches nothing passes, and so does one that has stopped reading.

	The two are indistinguishable from a green run, which is this project's own recorded lesson
	about a guard whose walk quietly narrowed — so this asks the scan for something that is
	certainly there and insists it finds it.
	"""

	found = _spelled("import sqlite3")

	assert len(found) > 3, (
		f"the scan found {len(found)} files importing sqlite3, which is too few — it has "
		f"stopped reading the tree, and every ban above would pass by matching nothing"
	)

