"""Every module declares what it names, and names what it declares.

**Ruff cannot see either half of this, and neither can mypy.** ``import a.b.c`` binds only
``a``, and ``a`` is used on nearly every line here, so F401 never fires for an import nobody
needs. In the other direction ``a.b.c.thing`` resolves perfectly well without ``import
a.b.c``, provided something *else* in the process has imported it — which is a property of
the whole program rather than of the file you are reading, and it changes when an unrelated
import is deleted three modules away.

CLAUDE.md has recorded the rule since M1 and called it manual. The release-candidate review
(`#193`, `#202`) found it broken in both directions in a dozen files, including one that would
have raised ``AttributeError``: ``domain/readiness.py`` names ``sqlalchemy.orm.aliased`` and
``import sqlalchemy`` alone does **not** bind ``sqlalchemy.orm``. It works today only because
the models it imports happen to import it.

**The interesting part is how "must be imported" is decided.** ``import os`` really does bind
``os.path``, and demanding a separate import for it would be a check that is wrong about the
standard library. So this does not carry a list of exceptions: it *asks*, in a fresh
interpreter, whether importing the parent alone makes the name available. A submodule a
package re-exports as part of its own contract passes; one that merely happens to be in
``sys.modules`` because of somebody else's import does not.

**Why this is not simply "Python would have told us".** Where the name is *evaluated* decides
whether it fails loudly or waits: an annotation or a module-level constant is evaluated at
import, so an undeclared module there is an immediate ``AttributeError`` — falsifying this
check with one produced exactly that, before pytest could run. Inside a function body nothing
is evaluated until the function is called, which is how ``domain/readiness.py`` carried
``sqlalchemy.orm.aliased`` with no import of its own: every caller happened to arrive through
a module that imported it, and the failure was waiting for the day one of them stopped.
"""

import ast
import collections
import functools
import json
import pathlib
import subprocess
import sys
import typing

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent

#: Where the rule is enforced. Tests are deliberately out: a test that names an undeclared
#: module fails the moment it runs, so the absence this guards against cannot survive there —
#: and their `conftest`/`api_support` imports would need exceptions that teach nothing.
CHECKED = ("src", "scripts")

#: Imports whose *purpose* is the import, with the reason each is not dead. An entry is a
#: ``(file, module)`` pair, and the reason is what makes adding one a decision.
#:
#: All three below are the same fact: SQLAlchemy's declarative metadata is populated by the
#: model modules being imported at all, so anything that builds or compares a schema has to
#: pull them in without naming them.
SIDE_EFFECT_IMPORTS: dict[tuple[str, str], str] = {
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.activity"): (
		"registers event and comment on Base.metadata; this package exists to gather them"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.identity"): (
		"registers workspace, user, role, membership and api_token, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.project"): (
		"registers project and project_member, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.system"): (
		"registers the instance singleton, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.vocabulary"): (
		"registers status, item_type and link_type, the same way"
	),
	("src/subroutine/db/models/__init__.py", "subroutine.db.models.work"): (
		"registers task, document, tag, link and mention, the same way"
	),
	("src/subroutine/db/fulltext.py", "sqlalchemy.dialects.postgresql"): (
		"registers the argument and return types of to_tsvector and its family; SQLAlchemy "
		"refuses to compile one constructed before this import, with a message naming it. "
		"Every probe missed it because creating a PostgreSQL engine imports it first — under "
		"the suite the models are built before any engine exists, and every PostgreSQL test "
		"errored"
	),
	("src/subroutine/db/migrate.py", "subroutine.db.models"): (
		"populates Base.metadata before the drift check compares it against the database; "
		"nothing here names a model"
	),
	("src/subroutine/db/migrations/env.py", "subroutine.db.models"): (
		"the same, for the target metadata Alembic autogenerates against"
	),
}


def _source_files () -> list[pathlib.Path]:
	"""Return every file the rule applies to."""

	found: list[pathlib.Path] = []

	for directory in CHECKED:
		for path in sorted((ROOT / directory).rglob("*.py")):
			# Generated by Alembic and following its conventions rather than ours (CLAUDE.md).
			if "versions" in path.parts:
				continue

			found.append(path)

	return found


def _module_name (path: pathlib.Path) -> str:
	"""Return the dotted name a file is importable as, or its stem outside the package.

	A module never has to import itself. ``scripts/`` is not a package and nothing there is
	importable as a dotted name, so its stem is answer enough — it will never match a chain.
	"""

	if (ROOT / "src") not in path.parents:
		return path.stem

	return ".".join(path.relative_to(ROOT / "src").with_suffix("").parts).removesuffix(
		".__init__"
	)


def _plain_imports (tree: ast.AST) -> set[str]:
	"""Return the modules a file imports as ``import x.y``, unaliased.

	Aliased and ``from`` imports are deliberately not counted. The house style permits both
	only in documented cases — a nested ``from X import Y as alias``, ``TYPE_CHECKING`` blocks
	— and in each of those the name being used is not a dotted module path, so neither half of
	this check has anything to say about them.
	"""

	return {
		alias.name
		for node in ast.walk(tree)
		if isinstance(node, ast.Import)
		for alias in node.names
		if alias.asname is None
	}


def _dotted_names (tree: ast.AST, roots: typing.Collection[str]) -> set[str]:
	"""Return every ``a.b.c`` chain in a file whose first segment is one of ``roots``.

	Rooted in what the file imports rather than in a list of package names. A chain can only
	begin with a module the file has bound, so this reaches exactly the names the rule is
	about and cannot mistake ``self.session.query`` or a local variable for one.
	"""

	found: set[str] = set()

	class Chains(ast.NodeVisitor):
		"""Collect attribute chains, longest form first."""

		def visit_Attribute (self, node: ast.Attribute) -> None:
			"""Walk one chain down to its root and record it if the root is imported."""

			parts: list[str] = []
			cursor: ast.expr = node

			while isinstance(cursor, ast.Attribute):
				parts.append(cursor.attr)
				cursor = cursor.value

			if isinstance(cursor, ast.Name) and cursor.id in roots:
				parts.append(cursor.id)
				parts.reverse()
				found.add(".".join(parts))

			self.generic_visit(node)

	Chains().visit(tree)

	return found


@functools.cache
def _is_module (candidate: str) -> bool:
	"""Report whether a dotted name is a module, without running any of it.

	**Our own package is answered from the source tree**, deliberately. ``find_spec`` *executes*
	the parent packages on the way to its answer, so pointing it at ``subroutine.x.y`` imports
	``subroutine.x`` — which makes a static check depend on the code it is checking, and turns
	any module-level failure in that code into a crash in the guard rather than a finding. It
	did exactly that while this was being written.

	Everything else is a third-party package that is already imported by the time this runs, so
	``find_spec`` costs nothing and reads no source of ours. The catch is broad because it can
	raise whatever an unrelated package's import raises, and none of that is this function's
	subject.
	"""

	parts = candidate.split(".")

	if parts[0] == "subroutine":
		inside = ROOT / "src" / pathlib.Path(*parts)

		return (inside / "__init__.py").is_file() or inside.with_suffix(".py").is_file()

	import importlib.util

	try:
		return importlib.util.find_spec(candidate) is not None

	except Exception:
		return False


def _module_prefixes (chain: str) -> tuple[str, ...]:
	"""Return the prefixes of a dotted name that are modules, longest last."""

	prefixes: list[str] = []
	parts = chain.split(".")

	for count in range(1, len(parts) + 1):
		candidate = ".".join(parts[:count])

		if not _is_module(candidate):
			break

		prefixes.append(candidate)

	return tuple(prefixes)


def _bound_by_its_parent (pairs: typing.Collection[str]) -> set[str]:
	"""Return the modules that importing only their top-level package already makes available.

	**Asked rather than listed**, and asked in a fresh interpreter, which is the whole point.
	``import os`` binds ``os.path`` because ``os`` says so; ``import sqlalchemy`` does not bind
	``sqlalchemy.orm``, and the difference is not something anybody should be maintaining by
	hand. A name that resolves here needs no import of its own; one that does not is being held
	up by somebody else's import and is one deletion away from an ``AttributeError``.

	One subprocess for the lot, and one fresh interpreter per *root* inside it, so that probing
	``sqlalchemy.engine`` cannot be what makes ``sqlalchemy.orm`` look bound.
	"""

	if not pairs:
		return set()

	probe = """
import importlib, json, sys

bound = []

for wanted in json.loads(sys.argv[1]):
	root = wanted.split(".")[0]

	# A fresh view per name: getattr on a package can trigger a lazy import, and one probe
	# leaving a submodule bound would make the next one pass for the wrong reason.
	for name in list(sys.modules):
		if name == root or name.startswith(root + "."):
			del sys.modules[name]

	try:
		found = importlib.import_module(root)

		for step in wanted.split(".")[1:]:
			found = getattr(found, step)

	except (ImportError, AttributeError):
		continue

	bound.append(wanted)

print(json.dumps(bound))
"""
	process = subprocess.Popen(
		[sys.executable, "-c", probe, json.dumps(sorted(pairs))],
		stdout=subprocess.PIPE,
		stderr=subprocess.PIPE,
		text=True,
	)
	# `communicate` rather than `wait`: a pipe left open trips the ResourceWarning this suite
	# turns into an error, and the traceback then points at the wrong place entirely.
	output, complaint = process.communicate(timeout=120)

	assert process.returncode == 0, complaint

	return set(json.loads(output))


def _undeclared () -> dict[str, set[str]]:
	"""Return, per file, every module it names without importing and without inheriting."""

	candidates: dict[str, set[str]] = collections.defaultdict(set)
	wanted: set[str] = set()

	for path in _source_files():
		relative = str(path.relative_to(ROOT))
		tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
		imported = _plain_imports(tree)
		roots = {name.split(".")[0] for name in imported}
		own = _module_name(path)

		for chain in _dotted_names(tree, roots):
			prefixes = _module_prefixes(chain)

			if not prefixes:
				continue

			named = prefixes[-1]

			if named == own or named in imported:
				continue

			# An import of something deeper binds every package along the way.
			if any(existing.startswith(named + ".") for existing in imported):
				continue

			candidates[relative].add(named)
			wanted.add(named)

	inherited = _bound_by_its_parent(wanted)

	return {
		path: undeclared
		for path, names in candidates.items()
		if (undeclared := names - inherited)
	}


def _unused () -> dict[str, set[str]]:
	"""Return, per file, every module it imports and never names."""

	found: dict[str, set[str]] = {}

	for path in _source_files():
		relative = str(path.relative_to(ROOT))
		tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
		imported = _plain_imports(tree)
		named = _dotted_names(tree, {name.split(".")[0] for name in imported})

		dead = {
			module
			for module in imported
			if not any(chain == module or chain.startswith(module + ".") for chain in named)
			if (relative, module) not in SIDE_EFFECT_IMPORTS
		}

		if dead:
			found[relative] = dead

	return found


def test_the_checker_reaches_the_whole_source_tree () -> None:
	"""Prove it visits what it thinks it does, before trusting either result.

	The lesson `#193` kept finding: a checker over somebody else's structure passes cheerfully
	while looking at nothing. ``tests/test_cli_help.py``'s first version walked the command tree
	with ``isinstance(x, click.Group)`` — Typer vendors its own click shim, so a ``TyperGroup``
	is not one — reported clean, and was checking one command out of forty-eight.

	So: a count, compared against reality, and a name that must be found in it.
	"""

	files = _source_files()

	assert len(files) > 90, f"only {len(files)} files reached; the tree is larger than that"
	assert any(path.name == "readiness.py" for path in files)

	tree = ast.parse((ROOT / "src" / "subroutine" / "domain" / "readiness.py").read_text())

	assert "sqlalchemy" in _plain_imports(tree)
	assert "sqlalchemy.orm.aliased" in _dotted_names(tree, {"sqlalchemy"})


def test_a_package_that_re_exports_a_submodule_needs_no_second_import () -> None:
	"""The exception is measured, not listed — and this is what says the measurement works.

	``import os`` binds ``os.path``; ``import sqlalchemy`` does not bind ``sqlalchemy.orm``.
	If this ever stops telling them apart, the check above becomes either a nuisance that
	demands imports the standard library does not need, or a rubber stamp.
	"""

	bound = _bound_by_its_parent({"os.path", "sqlalchemy.orm"})

	assert "os.path" in bound, "importing os really does bind os.path"
	assert "sqlalchemy.orm" not in bound, "and importing sqlalchemy does not bind its orm"


def test_no_module_names_something_it_has_not_imported () -> None:
	"""`#202`. A fully-qualified name that resolves through somebody else's import.

	It works until the import three modules away is deleted, and then it is an
	``AttributeError`` at the call site rather than at the change — with nothing about either
	file suggesting they were connected.
	"""

	undeclared = _undeclared()

	assert not undeclared, "\n".join(
		f"{path} names {', '.join(sorted(names))} without importing it"
		for path, names in sorted(undeclared.items())
	)


def test_no_module_imports_something_it_never_names () -> None:
	"""The other half, which ruff cannot see because ``import a.b.c`` binds only ``a``.

	Dead imports are cheap individually and expensive together: they are what makes the import
	block stop being a description of what a file depends on, and they are how a module that
	is *only* reached transitively comes to look deliberate.
	"""

	unused = _unused()

	assert not unused, "\n".join(
		f"{path} imports {', '.join(sorted(names))} and never names it"
		for path, names in sorted(unused.items())
	)


def test_every_side_effect_import_is_still_there () -> None:
	"""An exemption for an import that no longer exists is noise that hides signal."""

	stale = []

	for (relative, module), _reason in SIDE_EFFECT_IMPORTS.items():
		path = ROOT / relative

		if not path.is_file() or module not in _plain_imports(ast.parse(path.read_text())):
			stale.append(f"{relative} no longer imports {module}")

	assert not stale, "\n".join(stale)


@pytest.mark.parametrize("entry", sorted(SIDE_EFFECT_IMPORTS.items()))
def test_every_side_effect_import_says_why (entry: tuple[tuple[str, str], str]) -> None:
	"""A reason is what makes adding one a decision rather than a reflex."""

	(relative, module), reason = entry

	assert len(reason) > 8, f"{relative}'s {module} needs a reason, not a placeholder"
