"""refs are workspace-sequential integers

Revision ID: 0c8f7a7027e6
Revises: 233f898a2bee
Created: 2026-07-29 19:34:21.779793+00:00

Generated by Alembic and then edited by hand, because the automatic version could not
work: it altered ``ref`` straight from text to integer, and PostgreSQL will not cast
``'INBOX-1'`` to a number. Existing rows are therefore renumbered *while the column is
still text*, and only then does the type change.

docs/design.md §6.2. A ref used to be ``PROJECT-42``, minted from a counter on the project that
created the item. The prefix named something the item could be moved out of, so a task
moved elsewhere went on calling itself ``INBOX-2`` for the rest of its life. It is now a
plain integer drawn from a counter on the *workspace*, which an item cannot leave.

Unlike the rest of the project this file is space-indented and uses Alembic's own ``op``
convention rather than fully-qualified names: it is machine-generated, and
``batch_alter_table`` emits ``op.`` regardless of configuration, so a half-converted file
would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy


revision: str = '0c8f7a7027e6'
down_revision: str | None = '233f898a2bee'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: The two tables that draw from the ref counter, in the order a ref resolves in
#: (docs/design.md §6.2). Interpolated into SQL below, which is safe because these are literals
#: here and never reach this module from anywhere else.
WORK_TABLES = ('task', 'document')


def upgrade() -> None:
    """Apply this migration."""

    connection = op.get_bind()

    # The counter first, so there is somewhere to record where each workspace got to.
    # Added with a server default because the column is NOT NULL and existing rows need a
    # value; the default is dropped again at the end, since the model declares a
    # Python-side one and a stray server default would be a second source of truth.
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column(
                'next_ref_number', sqlalchemy.Integer(), nullable=False, server_default='1'
            )
        )

    _renumber(connection)

    for table in WORK_TABLES:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.drop_constraint(f'uq_{table}_origin_project_id_number', type_='unique')
            batch_op.drop_constraint(f'fk_{table}_origin_project_id_project', type_='foreignkey')
            batch_op.alter_column(
                'ref',
                existing_type=sqlalchemy.VARCHAR(length=64),
                type_=sqlalchemy.Integer(),
                existing_nullable=False,
                postgresql_using='ref::integer',
            )
            batch_op.drop_column('number')
            batch_op.drop_column('origin_project_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('next_ref_number')

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column(
            'next_ref_number',
            existing_type=sqlalchemy.Integer(),
            existing_nullable=False,
            server_default=None,
        )


def _renumber(connection: sqlalchemy.Connection) -> None:
    """Give every task and document a workspace-sequential number, oldest first.

    Refs are immutable by design, and this migration breaks that promise once — there is
    no way to carry ``INBOX-2`` forward into a scheme that has no prefixes. Ordering by
    creation time at least means the new numbers run in the order the work appeared, so a
    person's oldest item is ``#1``.

    Tasks and documents are numbered from one sequence, which is what makes a ref name
    exactly one thing.
    """

    workspaces = connection.execute(sqlalchemy.text('SELECT id FROM workspace')).scalars().all()

    union = ' UNION ALL '.join(
        f"SELECT '{table}' AS kind, id, created_at FROM {table} WHERE workspace_id = :workspace"
        for table in WORK_TABLES
    )

    for workspace in workspaces:
        rows = connection.execute(
            sqlalchemy.text(f'{union} ORDER BY created_at, id'), {'workspace': workspace}
        ).all()

        number = 0

        for number, row in enumerate(rows, start=1):
            connection.execute(
                sqlalchemy.text(f'UPDATE {row.kind} SET ref = :ref WHERE id = :id'),
                {'ref': str(number), 'id': row.id},
            )

        connection.execute(
            sqlalchemy.text(
                'UPDATE workspace SET next_ref_number = :next WHERE id = :id'
            ),
            {'next': number + 1, 'id': workspace},
        )


def downgrade() -> None:
    """Undo this migration.

    **This cannot restore what was there before, and does not pretend to.** Which project
    minted a given ref was thrown away by the upgrade, so the state rebuilt here is merely
    a *valid* one: every item is treated as having been minted by the project it currently
    sits in, and its old number becomes its new one. Refs stay unique — they were unique
    per workspace, so they are unique per project — but an item that had been moved comes
    back with a different ref from the one it went in with.
    """

    connection = op.get_bind()

    for table in WORK_TABLES:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.alter_column(
                'ref',
                existing_type=sqlalchemy.Integer(),
                type_=sqlalchemy.VARCHAR(length=64),
                existing_nullable=False,
                postgresql_using='ref::varchar',
            )
            batch_op.add_column(
                sqlalchemy.Column('number', sqlalchemy.INTEGER(), nullable=True)
            )
            batch_op.add_column(
                sqlalchemy.Column('origin_project_id', sqlalchemy.Uuid(), nullable=True)
            )

        connection.execute(
            sqlalchemy.text(
                f'UPDATE {table} SET number = CAST(ref AS INTEGER), origin_project_id = project_id'
            )
        )
        connection.execute(
            sqlalchemy.text(
                f'UPDATE {table} SET ref = ('
                f'  SELECT project.key || \'-\' || {table}.ref FROM project'
                f'  WHERE project.id = {table}.project_id'
                f')'
            )
        )

        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.alter_column('number', existing_type=sqlalchemy.INTEGER(), nullable=False)
            batch_op.alter_column(
                'origin_project_id', existing_type=sqlalchemy.Uuid(), nullable=False
            )
            batch_op.create_foreign_key(
                f'fk_{table}_origin_project_id_project',
                'project',
                ['origin_project_id'],
                ['id'],
                ondelete='RESTRICT',
            )
            batch_op.create_unique_constraint(
                f'uq_{table}_origin_project_id_number', ['origin_project_id', 'number']
            )

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column(
                'next_ref_number', sqlalchemy.INTEGER(), nullable=False, server_default='1'
            )
        )

    # Each project's counter has to clear every number it now owns, or the next create
    # collides with something that already exists.
    for table in WORK_TABLES:
        connection.execute(
            sqlalchemy.text(
                f'UPDATE project SET next_ref_number = ('
                f'  SELECT MAX({table}.number) + 1 FROM {table}'
                f'  WHERE {table}.origin_project_id = project.id'
                f') WHERE ('
                f'  SELECT MAX({table}.number) + 1 FROM {table}'
                f'  WHERE {table}.origin_project_id = project.id'
                f') > project.next_ref_number'
            )
        )

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column(
            'next_ref_number',
            existing_type=sqlalchemy.INTEGER(),
            existing_nullable=False,
            server_default=None,
        )

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_column('next_ref_number')
