"""A document may bind the whole workspace

Item ``#4133``, decision ``#4134``. A document carries ``binds``: ``project``, which every
document in existence is, or ``workspace``, which lists a rule in force for every reader of the
conventions wherever they stand.

**Added with a server default and then stripped of it**, as ``f2b8c1a94d63`` added
``starts_is_all_day``: the column is NOT NULL and the table has rows, and the model declares
only a Python-side default, so a default left behind would show as drift for ever.

**The CHECK is written out by hand**, because autogenerate does not compare CHECK constraints -
``migrate.check_constraint_differences`` does - and it is named by the suffix the naming
convention completes to ``ck_document_binds``.

Revision ID: 124f22afc629
Revises: 58c81c09d101
Created: 2026-10-02 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

import sqlalchemy
from alembic import op


revision: str = '124f22afc629'
down_revision: str | None = '58c81c09d101'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

document = sqlalchemy.table(
    'document',
    sqlalchemy.column('binds', sqlalchemy.String(length=16)),
)


def upgrade () -> None:
    """Add the column, with every document there is binding its project."""

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column(
                'binds',
                sqlalchemy.String(length=16),
                nullable=False,
                server_default='project',
            )
        )
        batch_op.create_check_constraint('binds', "binds IN ('project', 'workspace')")

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('binds', server_default=None)


def downgrade () -> None:
    """Refuse while any document binds the whole workspace, then take the column away.

    **Counted before anything changes**, which is ``SR#1689``'s rule: nothing on SQLite can be
    undone, so a mark the revision before cannot hold is refused rather than dropped.
    """

    connection = op.get_bind()
    marked = connection.scalar(
        sqlalchemy.select(sqlalchemy.func.count())
        .select_from(document)
        .where(document.c.binds == 'workspace')
    ) or 0

    if marked:
        raise RuntimeError(
            f"Cannot go back below this revision: {marked} document(s) bind the whole "
            "workspace, which the revision before cannot say. Set each back to its project "
            "first: subroutine doc edit <ref> --binds project."
        )

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_document_binds'), type_='check')
        batch_op.drop_column('binds')
