"""superseding a document is a link, not a column

Revision ID: 1f61c97bf2ca
Revises: 937352bb16de
Created: 2026-09-02 07:24:52.932476

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import datetime
import typing
import uuid

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '1f61c97bf2ca'
down_revision: str | None = '937352bb16de'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def _carry_the_chain_into_links(connection: sqlalchemy.engine.Connection) -> None:
    """Write a `supersedes` link for every document whose column says it replaced one.

    **The column is dropped below, so anything it holds has to move first or it is gone.**
    `SR#1684` measured zero of 226 documents using it on the instance this was written on —
    and that is the wrong instrument, because this migration also runs on installations
    nobody here can see, where a row may exist and where nobody would find out it had been
    deleted. A no-op there costs nothing; the alternative costs a fact.

    **The status is deliberately not moved.** Setting the column used to retire the document
    it named, as a side effect; `SR#1685` decided a link must not rewrite another row, and
    `SR#1684` retired the column rather than keeping the two behaviours side by side. So an
    already-superseded document keeps whatever status it has, which is the one it was given.

    **`created_by` is null on purpose.** A migration has no principal, and inventing one would
    put a person's name on a row they did not write — the same rule `SR#1415` states for an
    event's actor.
    """

    documents = sqlalchemy.table(
        "document",
        sqlalchemy.column("id"),
        sqlalchemy.column("workspace_id"),
        sqlalchemy.column("supersedes_id"),
        sqlalchemy.column("deleted_at"),
    )

    chained = connection.execute(
        sqlalchemy.select(
            documents.c.id, documents.c.workspace_id, documents.c.supersedes_id
        ).where(documents.c.supersedes_id.is_not(None), documents.c.deleted_at.is_(None))
    ).all()

    if not chained:
        return

    types = sqlalchemy.table(
        "link_type",
        sqlalchemy.column("id"),
        sqlalchemy.column("key"),
        sqlalchemy.column("workspace_id"),
    )
    available = {
        workspace: identifier
        for identifier, workspace in connection.execute(
            sqlalchemy.select(types.c.id, types.c.workspace_id).where(
                types.c.key == "supersedes"
            )
        ).all()
    }

    # **Refused before anything is written**, which is `SR#1689`'s rule and the only prevention
    # that works: SQLite runs a migration outside any transaction this code can roll back, so a
    # check *after* the drop could report the loss and never reverse it. A workspace that has
    # removed the seeded link type has nowhere to put the fact, and silently discarding it is
    # the one outcome nobody could detect afterwards.
    missing = sorted({str(row[1]) for row in chained if row[1] not in available})

    if missing:
        raise RuntimeError(
            "These workspaces have documents with a supersedes chain and no 'supersedes' link "
            f"type to move it into: {', '.join(missing)}. Seed the link type in each, then run "
            "this again — the alternative is dropping the column and losing what it says."
        )

    links = sqlalchemy.table(
        "link",
        sqlalchemy.column("id"),
        sqlalchemy.column("source_type"),
        sqlalchemy.column("source_id"),
        sqlalchemy.column("target_type"),
        sqlalchemy.column("target_id"),
        sqlalchemy.column("link_type_id"),
        sqlalchemy.column("created_at"),
        sqlalchemy.column("created_by"),
        sqlalchemy.column("workspace_id"),
        sqlalchemy.column("deleted_at"),
    )
    now = datetime.datetime.now(datetime.UTC).replace(tzinfo=None)

    for successor, workspace, superseded in chained:
        link_type = available[workspace]

        # The unique index ignores deleted rows, so this asks the same question it does:
        # a live link already saying this means the fact is carried and there is nothing to do.
        already = connection.execute(
            sqlalchemy.select(links.c.id).where(
                links.c.source_type == "document",
                links.c.source_id == successor,
                links.c.target_type == "document",
                links.c.target_id == superseded,
                links.c.link_type_id == link_type,
                links.c.deleted_at.is_(None),
            )
        ).first()

        if already is not None:
            continue

        connection.execute(
            links.insert().values(
                id=uuid.uuid4().hex,
                source_type="document",
                source_id=successor,
                target_type="document",
                target_id=superseded,
                link_type_id=link_type,
                created_at=now,
                created_by=None,
                workspace_id=workspace,
                deleted_at=None,
            )
        )


def upgrade() -> None:
    """Apply this migration."""

    _carry_the_chain_into_links(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_document_supersedes_id'), sqlite_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_constraint(batch_op.f('fk_document_supersedes_id_document'), type_='foreignkey')
        batch_op.drop_column('supersedes_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration.

    **The column comes back empty, and the links stay.** Reversing the carry would mean
    deleting links this migration may not have written — `supersedes` has been a link type
    since `a986838fadc4` and a person may have drawn one by hand — and there is no way to tell
    those apart. An empty column is the honest downgrade: nothing is lost, because the fact it
    used to hold is in the links either way.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        # **`uuid_column()`, not the `CHAR(32)` autogenerate wrote.** It reflected the type
        # from SQLite, where a uuid is stored as characters; on PostgreSQL `document.id` is a
        # real `uuid`, and a foreign key between the two is refused outright — measured, as
        # `DatatypeMismatch: foreign key constraint cannot be implemented`. The dual-backend
        # rule is what caught it, and it caught it on the *downgrade*, which is the half
        # nobody drives by hand.
        batch_op.add_column(sqlalchemy.Column('supersedes_id', subroutine.db.types.uuid_column(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_document_supersedes_id_document'), 'document', ['supersedes_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('uq_document_supersedes_id'), ['supersedes_id'], unique=1, sqlite_where=sqlalchemy.text('deleted_at IS NULL'))

    # ### end Alembic commands ###
