"""instance timezone; workspace timezone optional

Revision ID: 233f898a2bee
Revises: ea3e86ad12c4
Created: 2026-07-29 14:42:52.897916+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '233f898a2bee'
down_revision: str | None = 'ea3e86ad12c4'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('timezone', sqlalchemy.String(length=64), server_default='UTC', nullable=False))

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sqlalchemy.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # A workspace may have been left unset while the column allowed it, and the column is
    # about to stop allowing it. Without this backfill the downgrade fails on any
    # installation that used the feature this migration added.
    #
    # **From the instance, not from the literal 'UTC'.** Making this column nullable is what
    # let a workspace *inherit* the instance's zone, so a workspace reading NULL means "the
    # instance's", and writing UTC over it silently re-zones every inheriting workspace on an
    # instance that is not in UTC — a data change nobody asked for, in the operation that is
    # meant to put things back. Read before `instance.timezone` is dropped below.
    op.execute(
        "UPDATE workspace SET timezone = "
        "COALESCE((SELECT timezone FROM instance LIMIT 1), 'UTC') "
        "WHERE timezone IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sqlalchemy.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
