"""task assigner

Revision ID: 243497ffc330
Revises: 59c627e98f2d
Created: 2026-08-04 17:04:58.791972

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.

**No backfill, and that was measured rather than assumed** (`#477`). The fact is recoverable —
the event log carries every assignment change with its actor — but zero tasks on the only
instance in existence carry an assignee at all, so the walk would move nothing. A null here is
also the honest answer for a task assigned before anything recorded who did it, and decision
`#473` keeps the log as the history regardless, so nothing is lost by leaving it.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '243497ffc330'
down_revision: str | None = '59c627e98f2d'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('assigned_by_id', sqlalchemy.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_assigned_by_id_user'), 'user', ['assigned_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_assigned_by_id_user'), type_='foreignkey')
        batch_op.drop_column('assigned_by_id')

    # ### end Alembic commands ###
