"""Events past a retention floor move to an archive

Item ``#251``, decision ``#4233``. ``event_archive`` holds what an operator's
``events_retention_days`` has moved out of the change feed, column for column as ``event`` holds
it, and ``instance.events_archived_through`` the highest ``seq`` moved, which is what answers a
cursor at or below it with ``410 cursor_expired``.

**``seq`` is copied, never allocated**, so the archive's has no sequence: a second one would be a
second number for a copy to re-seat.

**Going back puts every archived event back in ``event``**, before the table goes, so the
revision before loses nothing it could hold. The highest ``seq`` moved goes with the column, and
the feed then answers from the first event again.

Revision ID: 340ff3f92fa6
Revises: 124f22afc629
Created: 2026-10-03 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

import sqlalchemy
from alembic import op

import subroutine.db.types


revision: str = '340ff3f92fa6'
down_revision: str | None = '124f22afc629'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

COLUMNS = (
    'seq', 'id', 'actor_user_id', 'actor_token_id', 'actor_interface', 'entity_type',
    'entity_id', 'subject_type', 'subject_id', 'subject_b_type', 'subject_b_id', 'action',
    'changes', 'created_at', 'workspace_id',
)


def upgrade () -> None:
    """Make the archive, empty, and the place the highest ``seq`` moved is recorded."""

    op.create_table('event_archive',
    sqlalchemy.Column('seq', sqlalchemy.BigInteger().with_variant(sqlalchemy.Integer(), 'sqlite'), autoincrement=False, nullable=False),
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('actor_user_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('actor_token_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('actor_interface', sqlalchemy.String(length=16), nullable=True),
    sqlalchemy.Column('entity_type', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('entity_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('subject_type', sqlalchemy.String(length=32), nullable=True),
    sqlalchemy.Column('subject_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('subject_b_type', sqlalchemy.String(length=32), nullable=True),
    sqlalchemy.Column('subject_b_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('action', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('changes', sqlalchemy.JSON(), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_event_archive_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('seq', name=op.f('pk_event_archive')),
    sqlalchemy.UniqueConstraint('id', name=op.f('uq_event_archive_id'))
    )
    with op.batch_alter_table('event_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_archive_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_event_archive_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('ix_event_archive_workspace_id_entity_type_entity_id_seq', ['workspace_id', 'entity_type', 'entity_id', 'seq'], unique=False)
        batch_op.create_index('ix_event_archive_workspace_id_seq', ['workspace_id', 'seq'], unique=False)
        batch_op.create_index('ix_event_archive_workspace_id_subject_type_subject_id_seq', ['workspace_id', 'subject_type', 'subject_id', 'seq'], unique=False)

    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('events_archived_through', sqlalchemy.BigInteger(), nullable=True))


def downgrade () -> None:
    """Put every archived event back in ``event``, then take the archive away."""

    archive = sqlalchemy.table('event_archive', *[sqlalchemy.column(name) for name in COLUMNS])
    live = sqlalchemy.table('event', *[sqlalchemy.column(name) for name in COLUMNS])
    op.get_bind().execute(live.insert().from_select(list(COLUMNS), sqlalchemy.select(archive)))

    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_column('events_archived_through')

    with op.batch_alter_table('event_archive', schema=None) as batch_op:
        batch_op.drop_index('ix_event_archive_workspace_id_subject_type_subject_id_seq')
        batch_op.drop_index('ix_event_archive_workspace_id_seq')
        batch_op.drop_index('ix_event_archive_workspace_id_entity_type_entity_id_seq')
        batch_op.drop_index('ix_event_archive_workspace_id_created_at')
        batch_op.drop_index(batch_op.f('ix_event_archive_workspace_id'))

    op.drop_table('event_archive')
