"""A workspace can prioritise one project

One project's work rises in this workspace's ranked listings (item ``#986``, decision
``#982``). A single nullable pointer rather than a flag on the project, because one column
holds one value: choosing B unsets A atomically, which is the radio-button semantic with no
clearing logic and no unique index to get wrong.

``ON DELETE SET NULL`` so the state cannot outlive its subject, and ``use_alter`` because
this constraint closes a foreign-key cycle — ``project`` references ``status``, ``status``
references ``workspace``, and this closes the loop. The flag marks the cycle as known, so
the constraint is created by its own ``ALTER`` and the schema can still be ordered.

Nothing is backfilled. Null is the state every existing workspace should be in: no project
was prioritised before this column existed, so there is no earlier fact to recover.

Revision ID: 3a3d6accc196
Revises: f159c8635e54
Created: 2026-08-18 16:28:20.888985+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '3a3d6accc196'
down_revision: str | None = 'f159c8635e54'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('prioritised_project_id', sqlalchemy.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_workspace_prioritised_project_id_project'), 'project', ['prioritised_project_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workspace_prioritised_project_id_project'), type_='foreignkey')
        batch_op.drop_column('prioritised_project_id')

    # ### end Alembic commands ###
