"""a link event names both of its ends

Revision ID: 4240ca248de1
Revises: a1b3cef13c45
Created: 2026-08-24 16:40:25.145538+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '4240ca248de1'
down_revision: str | None = 'a1b3cef13c45'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


#: Name the far end of every link event that has a subject, reading the **link row**.
#:
#: Not out of ``changes``: that holds *refs*, which would need a lookup per row and a guess
#: about whether the number names a task or a document — and it is absent entirely on a
#: withdrawal, which records no changes at all. The row holds ids and both kinds outright.
#:
#: This is safe because a link is **soft**-deleted, so the row survives every unlink. The
#: ``EXISTS`` is belt and braces: a row that somehow has no link left keeps a null pair, which
#: is exactly the pre-migration rule and hides nothing it did not already hide.
#:
#: A correlated subquery in ``SET``, which both backends run. Two of them rather than one,
#: because SQLite has no row-valued ``SET (a, b) = (SELECT …)``.
BACKFILL = """
UPDATE event
SET subject_b_type = (
        SELECT CASE WHEN link.target_id = event.subject_id
                    THEN link.source_type ELSE link.target_type END
        FROM link WHERE link.id = event.entity_id
    ),
    subject_b_id = (
        SELECT CASE WHEN link.target_id = event.subject_id
                    THEN link.source_id ELSE link.target_id END
        FROM link WHERE link.id = event.entity_id
    )
WHERE event.entity_type = 'link'
  AND event.subject_id IS NOT NULL
  AND EXISTS (SELECT 1 FROM link WHERE link.id = event.entity_id)
"""


def upgrade() -> None:
    """Let an event say it happened on two items, so a link's can be scoped by both.

    A link event carries one subject, and one subject expresses one item's visibility — but a
    link's visibility is the *conjunction* of two items'. So an event whose source somebody
    could see reported the ``target``'s ref in ``changes``, and a reader entitled to one end
    learned that a particular item they could not see existed and was joined to it.

    The pair is null on every other kind of write and nothing in ``scoping.visible_events``
    knows what a link is: the rule it gains is *if a second subject is set it must be visible
    too*, which anything that later happens to two items inherits for nothing.

    **The backfill takes the end that is not the subject**, which is what makes an inverse
    link fall out rather than needing a case: somebody withdrawing an *incoming* link stands
    on the target, so the event already names the target and the far end is the source.

    Link events written before there were subjects at all keep a null pair. They match no
    clause in the feed and reach nobody already, so naming a far end for them would be
    inventing a claim about what somebody did in order to hide something already hidden.
    """

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column("subject_b_type", sqlalchemy.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sqlalchemy.Column("subject_b_id", subroutine.db.types.uuid_column(), nullable=True)
        )

    op.execute(sqlalchemy.text(BACKFILL))


def downgrade() -> None:
    """Drop the second subject, and with it the conjunction it expressed.

    Lossy in the way that matters: the columns go, so every link event is once again as
    visible as one of its two ends. Nothing else read them, so nothing else breaks.
    """

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("subject_b_id")
        batch_op.drop_column("subject_b_type")
