"""an item type says what kind of thing it is

`SR#1134`, building decision `SR#1133`. ``item_type.category`` is what a client branches on when
it does not recognise the key — a workspace that invents ``epic`` should get a picture that means
something rather than the glyph for *unknown* for ever.

**Three steps rather than one, and the middle one is the point.** Alembic's autogenerated version
adds the column NOT NULL with no default, which fails on every database that has a workspace in
it — and every database has, because ``init`` seeds eleven of these rows per workspace. So the
column arrives nullable, the eleven seeded keys are filled in from decision `SR#1133`'s table,
and only then does it become NOT NULL.

**The fallback is the default type's category and it should never fire.** Nothing in the product
can create an item type today — that is `SR#1129` — so every row is one of the eleven. A row
that is not is either hand-inserted or from a future this migration cannot see, and leaving it
NULL would fail the ``ALTER`` with a message about a constraint rather than about the row.

**And the CHECK is written out because Alembic does not compare CHECK constraints.** The
vocabulary lives in one, so an ``enum_check`` that only ever reached the models would pass the
whole suite and never reach a migrated database. ``migrate.check_constraint_differences`` is what
catches that, and it is what this line exists to satisfy.

Revision ID: 491e1a09de04
Revises: a01dcd83a946
Created: 2026-08-23 19:30:03.139389+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy


revision: str = '491e1a09de04'
down_revision: str | None = 'a01dcd83a946'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: Decision `SR#1133`'s table. Task-side this is Simon's own naming rule of 2026-07-31 with the
#: types collected under each clause; document-side it is what a title of that kind states.
CATEGORIES = {
    'task': 'work',
    'bug': 'defect',
    'feature': 'work',
    'chore': 'work',
    'spike': 'question',
    'note': 'record',
    'spec': 'reference',
    'design': 'reference',
    'decision': 'decision',
    'finding': 'record',
    'dead_end': 'decision',
}

#: What an unrecognised key falls back to: the category of the type that entity's rows default
#: to — ``task`` for a task and ``note`` for a document. Unreachable today, and here so that the
#: NOT NULL below cannot fail on a row this table did not anticipate.
FALLBACK = {'task': 'work', 'document': 'record'}

VALUES = "'work', 'defect', 'question', 'decision', 'reference', 'record'"


def upgrade () -> None:
    """Give every item type a category, then hold the column to the vocabulary."""

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column('category', sqlalchemy.String(length=16), nullable=True)
        )

    for key, category in CATEGORIES.items():
        op.execute(
            sqlalchemy.text(
                'UPDATE item_type SET category = :category WHERE key = :key'
            ).bindparams(category=category, key=key)
        )

    for entity_type, category in FALLBACK.items():
        op.execute(
            sqlalchemy.text(
                'UPDATE item_type SET category = :category '
                'WHERE category IS NULL AND entity_type = :entity_type'
            ).bindparams(category=category, entity_type=entity_type)
        )

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.alter_column(
            'category', existing_type=sqlalchemy.String(length=16), nullable=False
        )
        batch_op.create_check_constraint('category', f'category IN ({VALUES})')


def downgrade () -> None:
    """Take it back out. Nothing else reads it, so nothing else has to move."""

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_item_type_category'), type_='check')
        batch_op.drop_column('category')
