"""The Inbox is public, at the top level and out of the trash

Item ``#4549``, decision ``#4532``. ``ck_project_inbox_settled`` holds beneath the program what
``projects.refuse_unsettling_the_inbox`` refuses by name: everything filed in a workspace without a
project goes to its Inbox, so everybody in the workspace has to be able to reach it.

**An Inbox that already breaks it is refused before anything is written** (Simon, 2026-10-06).
The program refused making one private, or moving it under another project, only from 0.10.0, so
an installation older than that can hold one, and the constraint would fail on it naming a
constraint rather than the Inbox. Settling it here would show a private Inbox's work to the whole
workspace with nobody choosing that, so each is named, with the statements that settle it.

**The CHECK is written out by hand**, because autogenerate does not compare CHECK constraints -
``migrate.check_constraint_differences`` does - and it is named by the suffix the naming
convention completes to ``ck_project_inbox_settled``.

Revision ID: 4b82edddbc80
Revises: 6c708db1582c
Created: 2026-10-06 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

import sqlalchemy
from alembic import op


revision: str = '4b82edddbc80'
down_revision: str | None = '6c708db1582c'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: What the constraint holds, as the model declares it.
SETTLED = "NOT is_inbox OR (visibility = 'public' AND parent_id IS NULL AND deleted_at IS NULL)"


def _settling (row: typing.Any) -> tuple[list[str], list[str]]:
    """Say what is wrong with one Inbox, and the statements that settle it.

    **Moving it to the top is the move ``hierarchy.reparent`` makes**, spelled out: its own segment
    becomes the whole path, every row beneath it keeps its tail, and every depth shifts by as much.
    The path's segments are the ids as the program wrote them, so the new prefix is read off the old
    path rather than rebuilt from a column a backend may store in another shape.
    """

    wrong: list[str] = []
    statements: list[str] = []

    if row.visibility != 'public':
        wrong.append(f"it is {row.visibility}")
        statements.append(f"UPDATE project SET visibility = 'public' WHERE id = '{row.id}';")

    if row.parent_id is not None:
        segments = [segment for segment in row.path.split('/') if segment]
        top = f"/{segments[-1]}/"
        wrong.append("it is under another project")
        statements.append(
            f"UPDATE project SET path = '{top}' || substr(path, {len(row.path) + 1}), "
            f"depth = depth - {len(segments) - 1} "
            f"WHERE workspace_id = '{row.workspace_id}' AND path LIKE '{row.path}%';"
        )
        statements.append(f"UPDATE project SET parent_id = NULL WHERE id = '{row.id}';")

    if row.deleted_at is not None:
        wrong.append("it is in the trash")
        statements.append(f"UPDATE project SET deleted_at = NULL WHERE id = '{row.id}';")

    return wrong, statements


def upgrade () -> None:
    """Hold every Inbox public, at the top level and out of the trash, refusing first if one is not."""

    unsettled = op.get_bind().execute(
        sqlalchemy.text(
            "SELECT workspace.slug, project.id, project.workspace_id, project.visibility, "
            "project.parent_id, project.deleted_at, project.path "
            "FROM project JOIN workspace ON workspace.id = project.workspace_id "
            "WHERE project.is_inbox AND (project.visibility <> 'public' "
            "OR project.parent_id IS NOT NULL OR project.deleted_at IS NOT NULL) "
            "ORDER BY workspace.slug"
        )
    ).all()

    if unsettled:
        lines = [
            "This installation has an Inbox that is not public, at the top level and out of the "
            "trash, which this version holds every Inbox to: everything filed in a workspace "
            "without a project goes there, so everybody in it has to be able to reach it. Nothing "
            "has been changed. Making an Inbox public shows its work to the whole workspace, so "
            "that is yours to choose: run these statements against this database, then run this "
            "again.",
        ]

        for row in unsettled:
            wrong, statements = _settling(row)
            lines.append(f"The Inbox of '{row.slug}': {', and '.join(wrong)}.")
            lines.extend(f"    {statement}" for statement in statements)

        raise RuntimeError("\n".join(lines))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_check_constraint('inbox_settled', SETTLED)


def downgrade () -> None:
    """Let an Inbox be anything again, as far as the database is concerned."""

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_project_inbox_settled'), type_='check')
