"""an event carries the subject it happened on

Revision ID: 547fe53b263c
Revises: 0c8f7a7027e6
Created: 2026-08-01 07:19:51.793184+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing
import uuid

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '547fe53b263c'
down_revision: str | None = '0c8f7a7027e6'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration, moving every comment event's subject into its own columns.

    Until now a comment's event said what it was made on inside ``changes``, as
    ``{"on": {"from": null, "to": "task:<uuid>"}}``, where nothing could join on it. The
    columns are what put a comment into the commented-on item's history, so without this
    backfill every comment written before today would stay invisible there for good — which
    is most of the reason the history was wrong in the first place.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('subject_type', sqlalchemy.String(length=32), nullable=True))
        batch_op.add_column(sqlalchemy.Column('subject_id', sqlalchemy.Uuid(), nullable=True))
        batch_op.create_index('ix_event_workspace_id_subject_type_subject_id_seq', ['workspace_id', 'subject_type', 'subject_id', 'seq'], unique=False)

    # ### end Alembic commands ###

    _move_subjects(forwards=True)


def downgrade() -> None:
    """Undo this migration, putting each subject back where it used to be recorded.

    Written rather than left to the generator because the generated version drops two
    columns holding the only copy of a fact. A downgrade nobody will run is still a
    downgrade that should not lose the audit trail it was pointed at.
    """

    _move_subjects(forwards=False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_workspace_id_subject_type_subject_id_seq')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('subject_type')

    # ### end Alembic commands ###


def _events() -> sqlalchemy.TableClause:
    """The columns of ``event`` this migration touches, named rather than reflected.

    A migration reads the schema *of its own moment*, so it declares what it needs instead
    of importing the model — which describes head and would drift out from under this file
    the next time the table grows a column.
    """

    return sqlalchemy.table(
        'event',
        sqlalchemy.column('seq', sqlalchemy.BigInteger),
        sqlalchemy.column('entity_type', sqlalchemy.String),
        sqlalchemy.column('entity_id', subroutine.db.types.uuid_column()),
        sqlalchemy.column('subject_type', sqlalchemy.String),
        sqlalchemy.column('subject_id', subroutine.db.types.uuid_column()),
        sqlalchemy.column('changes', subroutine.db.types.json_column()),
        sqlalchemy.column('action', sqlalchemy.String),
    )


def _move_subjects(*, forwards: bool) -> None:
    """Carry each comment event's subject between ``changes['on']`` and the columns.

    Done row by row in Python rather than in SQL because one side of it lives inside a JSON
    document, and the two backends spell that access differently enough that a single
    statement could not serve both. There is one event per thing ever done to a comment, so
    the cost is a few hundred rows on the largest instance this release will meet.
    """

    events = _events()
    connection = op.get_bind()

    selected = sqlalchemy.select(
        events.c.seq,
        events.c.entity_id,
        events.c.subject_type,
        events.c.subject_id,
        events.c.changes,
        events.c.action,
    ).where(events.c.entity_type == 'comment')

    subjects = _subjects(connection) if forwards else {}

    for row in connection.execute(selected).mappings().all():
        values = _forwards(row, subjects) if forwards else _backwards(row)

        if values is not None:
            connection.execute(
                sqlalchemy.update(events).where(events.c.seq == row['seq']).values(**values)
            )


def _subjects(connection: sqlalchemy.Connection) -> dict[uuid.UUID, tuple[str, uuid.UUID]]:
    """Return what every comment was made on, read from the comment table itself.

    **The authority, rather than ``changes['on']``, and that is the difference between a
    partial backfill and a complete one.** Only a comment's *creation* ever wrote the subject
    into its changes, so parsing those left every edit and deletion unattributed — two rows
    on the instance this was written against, and proportionally more on one where comments
    get corrected. Nothing here hard-deletes, so the comment row is always still there to
    ask. The parsed form remains the fallback for a comment that somehow is not.
    """

    comments = sqlalchemy.table(
        'comment',
        sqlalchemy.column('id', subroutine.db.types.uuid_column()),
        sqlalchemy.column('entity_type', sqlalchemy.String),
        sqlalchemy.column('entity_id', subroutine.db.types.uuid_column()),
    )
    found = connection.execute(
        sqlalchemy.select(comments.c.id, comments.c.entity_type, comments.c.entity_id)
    )

    return {row.id: (row.entity_type, row.entity_id) for row in found}


def _forwards(
    row: sqlalchemy.RowMapping, subjects: dict[uuid.UUID, tuple[str, uuid.UUID]]
) -> dict[str, typing.Any] | None:
    """Return the columns for one comment event, and drop the copy inside ``changes``."""

    changes = dict(row['changes'] or {})
    written = changes.pop('on', None)
    subject = subjects.get(row['entity_id']) or _parsed(written)

    if subject is None:
        # An unattributable event is left exactly as it was found. A migration that discards
        # a row it could not read turns a puzzling audit entry into a missing one.
        return None

    return {
        'subject_type': subject[0],
        'subject_id': subject[1],
        'changes': changes or None,
    }


def _parsed(written: typing.Any) -> tuple[str, uuid.UUID] | None:
    """Read the older ``{"on": {"to": "<type>:<uuid>"}}`` form, or report that it is not there."""

    stated = written.get('to') if isinstance(written, dict) else None

    if not isinstance(stated, str) or ':' not in stated:
        return None

    subject_type, _, subject_id = stated.partition(':')

    try:
        return subject_type, uuid.UUID(subject_id)

    except ValueError:
        return None


def _backwards(row: sqlalchemy.RowMapping) -> dict[str, typing.Any] | None:
    """Return the columns to the ``changes['on']`` shape the older schema recorded.

    Only onto a creation, which is the only action that ever carried it. Writing it onto an
    edit or a deletion would hand the older schema a row it could never have produced.
    """

    if row['action'] != 'created' or row['subject_type'] is None or row['subject_id'] is None:
        return None

    changes = dict(row['changes'] or {})
    changes['on'] = {'from': None, 'to': f"{row['subject_type']}:{row['subject_id']}"}

    return {'changes': changes}
