"""a milestone is a kind of task that includes work

`SR#3393`, building decision `SR#3391`. Three rows per workspace, and two CHECKs widened to
admit them:

- a ``milestone`` item type, in a new category, ``target``, which readiness is to read so that a
  milestone is never offered as work, whether or not anything is in it yet;
- an ``includes`` link type, *Includes* / *Included in*, in a new category, ``counting``, which
  a milestone's progress is to read;
- ``precedes``, *Precedes* / *Follows*, the planned order that holds nothing up. It is the
  relation `SR#1151` asked every workspace to be given, and one workspace had made for itself.

**The categories arrive before anything reads them.** A category the CHECK refuses cannot be
seeded at all, so the vocabulary goes first and the behaviour follows in the rest of
`SR#3392`.

**A workspace that already has one of these keys keeps its own row.** The seeder is idempotent
by key, and a key somebody chose is their vocabulary rather than ours to rewrite: a hand-made
``milestone`` type under ``work`` stays under ``work``. So the downgrade takes away only what
this added, which is what ``is_system`` marks.

**A workspace migrated by this stays at its seed version and has the rows anyway**, as
`SR#1236`'s and `SR#1688`'s migrations left theirs. The seeder finds them present, writes
nothing and moves the number up.

**The literals are written out rather than imported**, which is `SR#1134`'s precedent: a
migration is a statement about one moment, and importing ``seed`` or ``mixins`` would make this
file's behaviour change retroactively the day somebody edits a constant. The suite compares
what the two produce rather than trusting either.

Revision ID: 58c81c09d101
Revises: cfeea5d4dd35
Created: 2026-09-23 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import datetime
import typing
import uuid

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '58c81c09d101'
down_revision: str | None = 'cfeea5d4dd35'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: What each column admitted before this, and after it. Written out for the reason above, and
#: because Alembic's autogenerate does not compare CHECK constraints at all.
TYPES_BEFORE = "'work', 'defect', 'question', 'occasion', 'decision', 'reference', 'record'"
TYPES_AFTER = (
    "'work', 'defect', 'question', 'occasion', 'target', 'decision', 'reference', 'record'"
)
LINKS_BEFORE = "'gating', 'ordering', 'governing', 'describing'"
LINKS_AFTER = "'gating', 'ordering', 'counting', 'governing', 'describing'"

#: The categories this admits, which nothing may still use when it is taken back.
TYPE_CATEGORY = 'target'
LINK_CATEGORY = 'counting'

#: Seed set 4's item type. Not ``is_default``: nothing is filed as a milestone unless somebody
#: asks for one.
MILESTONE = {'entity_type': 'task', 'key': 'milestone', 'label': 'Milestone', 'category': 'target'}

#: Seed set 4's link types. Neither is symmetric: each end says something different.
LINK_TYPES = (
    {
        'key': 'includes',
        'title': 'Includes',
        'inverse_title': 'Included in',
        'category': 'counting',
    },
    {
        'key': 'precedes',
        'title': 'Precedes',
        'inverse_title': 'Follows',
        'category': 'ordering',
    },
)

#: The space left between two seeded positions, so a workspace can insert its own between them
#: later. ``mixins.POSITION_GAP`` at the time of writing, copied deliberately.
POSITION_GAP = 1000

#: Enough of each table to write one row, declared here rather than reflected: a migration runs
#: against a schema the models may have moved past, and the UUID and datetime types have to be
#: the ones both backends store.
item_type = sqlalchemy.table(
    'item_type',
    sqlalchemy.column('id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('entity_type', sqlalchemy.String(length=16)),
    sqlalchemy.column('key', sqlalchemy.String(length=64)),
    sqlalchemy.column('label', sqlalchemy.String(length=128)),
    sqlalchemy.column('category', sqlalchemy.String(length=16)),
    sqlalchemy.column('position', sqlalchemy.Integer()),
    sqlalchemy.column('is_default', sqlalchemy.Boolean()),
    sqlalchemy.column('is_system', sqlalchemy.Boolean()),
    sqlalchemy.column('created_at', subroutine.db.types.UtcDateTime()),
    sqlalchemy.column('updated_at', subroutine.db.types.UtcDateTime()),
)

link_type = sqlalchemy.table(
    'link_type',
    sqlalchemy.column('id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('key', sqlalchemy.String(length=64)),
    sqlalchemy.column('title', sqlalchemy.String(length=128)),
    sqlalchemy.column('inverse_title', sqlalchemy.String(length=128)),
    sqlalchemy.column('category', sqlalchemy.String(length=16)),
    sqlalchemy.column('is_symmetric', sqlalchemy.Boolean()),
    sqlalchemy.column('is_system', sqlalchemy.Boolean()),
    sqlalchemy.column('created_at', subroutine.db.types.UtcDateTime()),
    sqlalchemy.column('updated_at', subroutine.db.types.UtcDateTime()),
)

#: Read only to find every workspace, as `SR#1688`'s migration did.
status = sqlalchemy.table(
    'status',
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
)

#: Enough of the two referring tables to ask whether anything is using the rows below.
task = sqlalchemy.table(
    'task',
    sqlalchemy.column('type_id', subroutine.db.types.uuid_column()),
)

link = sqlalchemy.table(
    'link',
    sqlalchemy.column('link_type_id', subroutine.db.types.uuid_column()),
)


def upgrade () -> None:
    """Admit the two categories, then give every existing workspace the rows that use them."""

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_item_type_category'), type_='check')
        batch_op.create_check_constraint('category', f'category IN ({TYPES_AFTER})')

    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_link_type_category'), type_='check')
        batch_op.create_check_constraint('category', f'category IN ({LINKS_AFTER})')

    connection = op.get_bind()
    now = datetime.datetime.now(datetime.UTC)

    # Where each workspace's task types have got to, so the new one goes after them rather
    # than on top of one. A workspace with no task types at all cannot happen - `init` seeds
    # five - but `or 0` is what stops this being a claim rather than a query.
    highest = dict(
        connection.execute(
            sqlalchemy.select(
                item_type.c.workspace_id, sqlalchemy.func.max(item_type.c.position)
            )
            .where(item_type.c.entity_type == 'task')
            .group_by(item_type.c.workspace_id)
        ).tuples().all()
    )

    typed = set(
        connection.scalars(
            sqlalchemy.select(item_type.c.workspace_id).where(
                item_type.c.entity_type == 'task', item_type.c.key == MILESTONE['key']
            )
        )
    )

    rows = [
        {
            'id': uuid.uuid4(),
            'workspace_id': workspace_id,
            **MILESTONE,
            'position': (position or 0) + POSITION_GAP,
            'is_default': False,
            'is_system': True,
            'created_at': now,
            'updated_at': now,
        }
        for workspace_id, position in highest.items()
        if workspace_id not in typed
    ]

    if rows:
        connection.execute(sqlalchemy.insert(item_type), rows)

    # **Every workspace, read from the status table rather than from `workspace`**, as
    # `SR#1688`'s migration did. A link type is not scoped by entity type and carries no
    # position, so there is nothing to order against.
    everywhere = set(connection.scalars(sqlalchemy.select(status.c.workspace_id).distinct()))

    for seeded in LINK_TYPES:
        already = set(
            connection.scalars(
                sqlalchemy.select(link_type.c.workspace_id).where(
                    link_type.c.key == seeded['key']
                )
            )
        )

        edges = [
            {
                'id': uuid.uuid4(),
                'workspace_id': workspace_id,
                **seeded,
                'is_symmetric': False,
                'is_system': True,
                'created_at': now,
                'updated_at': now,
            }
            for workspace_id in sorted(everywhere - already)
        ]

        if edges:
            connection.execute(sqlalchemy.insert(link_type), edges)


def _count (connection: typing.Any, table: typing.Any, *where: typing.Any) -> int:
    """Return how many rows of ``table`` match."""

    return connection.scalar(
        sqlalchemy.select(sqlalchemy.func.count()).select_from(table).where(*where)
    ) or 0


def downgrade () -> None:
    """Refuse while anything uses what this added, then take it away and narrow both columns.

    **Every count is made before anything is deleted**, which is `SR#1689`'s rule: SQLite's
    foreign keys are off while a migration runs, so a delete PostgreSQL refuses, SQLite
    performs, and nothing here can be undone afterwards.

    **Four things refuse, not two.** A task typed ``milestone`` and a link drawn with
    ``includes`` or the seeded ``precedes`` are the rows this deletes. A type or a link type a
    workspace made for itself under ``target`` or ``counting`` is not this migration's to
    delete, but narrowing the CHECK would leave it outside what the column admits - so it
    refuses too, and says which.
    """

    connection = op.get_bind()

    types = list(
        connection.scalars(
            sqlalchemy.select(item_type.c.id).where(
                item_type.c.entity_type == 'task',
                item_type.c.key == MILESTONE['key'],
                item_type.c.is_system.is_(True),
            )
        )
    )
    keys = [seeded['key'] for seeded in LINK_TYPES]
    edges = list(
        connection.scalars(
            sqlalchemy.select(link_type.c.id).where(
                link_type.c.key.in_(keys), link_type.c.is_system.is_(True)
            )
        )
    )

    typed = _count(connection, task, task.c.type_id.in_(types)) if types else 0
    linked = _count(connection, link, link.c.link_type_id.in_(edges)) if edges else 0
    kept_types = _count(
        connection,
        item_type,
        item_type.c.category == TYPE_CATEGORY,
        item_type.c.is_system.is_not(True),
    )
    kept_links = _count(
        connection,
        link_type,
        link_type.c.category == LINK_CATEGORY,
        link_type.c.is_system.is_not(True),
    )

    if typed or linked or kept_types or kept_links:
        raise RuntimeError(
            f"Cannot go back below this revision: {typed} task(s) are "
            f"'{MILESTONE['key']}', {linked} link(s) use {' or '.join(keys)}, and "
            f"{kept_types} type(s) and {kept_links} link type(s) of a workspace's own are in "
            f"the '{TYPE_CATEGORY}' or '{LINK_CATEGORY}' category. Give those tasks another "
            f"type, remove those links, and move or remove those types first."
        )

    op.execute(link_type.delete().where(link_type.c.id.in_(edges)))
    op.execute(item_type.delete().where(item_type.c.id.in_(types)))

    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_link_type_category'), type_='check')
        batch_op.create_check_constraint('category', f'category IN ({LINKS_BEFORE})')

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_item_type_category'), type_='check')
        batch_op.create_check_constraint('category', f'category IN ({TYPES_BEFORE})')
