"""accountability chain

Revision ID: 59c627e98f2d
Revises: d5d0458f5ad5
Created: 2026-08-04 16:18:08.419735

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.

The backfill below is hand-written. `#476`, decision `#473`.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '59c627e98f2d'
down_revision: str | None = 'd5d0458f5ad5'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('responsible_user_id', sqlalchemy.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_responsible_user_id'), ['responsible_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_responsible_user_id_user'), 'user', ['responsible_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    _adopt_existing_agents()


def _adopt_existing_agents() -> None:
    """Give every service account already in the database somebody who answers for it.

    **The fact is not in the table**, which is what makes this a policy rather than a backfill
    in `547fe53b263c`'s sense: nothing has ever recorded who created a service account, so there
    is nothing to read back. The rule is therefore stated rather than derived — every existing
    agent becomes answerable to the sole active superuser, *where there is exactly one*.

    Where there is not, the column is left null and the agents are named in the output. Guessing
    between two administrators would put somebody's name against work they did not authorise,
    which is precisely what this column exists to make impossible.

    A null here is not a quiet default: an agent with nobody answering for it is refused by
    ``domain.accountability`` at its next authentication, which is the behaviour decision `#473`
    asked for. Better a stopped agent than an untraceable one.
    """

    bind = op.get_bind()
    users = sqlalchemy.table(
        "user",
        sqlalchemy.column("id", sqlalchemy.Uuid()),
        sqlalchemy.column("username", sqlalchemy.String()),
        sqlalchemy.column("is_service_account", sqlalchemy.Boolean()),
        sqlalchemy.column("is_superuser", sqlalchemy.Boolean()),
        sqlalchemy.column("is_active", sqlalchemy.Boolean()),
        sqlalchemy.column("deleted_at", subroutine.db.types.UtcDateTime()),
        sqlalchemy.column("responsible_user_id", sqlalchemy.Uuid()),
    )

    agents = bind.execute(
        sqlalchemy.select(users.c.id, users.c.username).where(
            users.c.is_service_account.is_(True), users.c.deleted_at.is_(None)
        )
    ).all()

    if not agents:
        return

    owners = bind.execute(
        sqlalchemy.select(users.c.id, users.c.username).where(
            users.c.is_superuser.is_(True),
            users.c.is_active.is_(True),
            users.c.is_service_account.is_(False),
            users.c.deleted_at.is_(None),
        )
    ).all()

    if len(owners) != 1:
        named = ", ".join(username for _id, username in agents)
        print(
            f"  {len(agents)} service account(s) have nobody answering for them: {named}. "
            f"This instance has {len(owners)} active superusers, so there is no unambiguous "
            f"answer and guessing one would be worse than leaving it. Set it before these "
            f"agents next authenticate, or they will be refused."
        )

        return

    owner_id, owner_name = owners[0]

    bind.execute(
        users.update()
        .where(users.c.is_service_account.is_(True), users.c.responsible_user_id.is_(None))
        .values(responsible_user_id=owner_id)
    )

    print(f"  {len(agents)} service account(s) are now answerable to {owner_name}.")


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_responsible_user_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_responsible_user_id'))
        batch_op.drop_column('responsible_user_id')

    # ### end Alembic commands ###
