"""a project carries no dates of its own

`SR#917` and `SR#525`, executing decision `SR#1131`. `project.start_at`, `project.due_at`
and `project.timezone` were mapped in the initial commit and assigned by nothing in the
whole history — no request model accepted one, no view reported one, and outside the model
the only references anywhere were three excuses in ``tests/test_api_writability.py``. So a
project had a start date, a deadline and a locality that could not be set, could not be
read, and appeared in no response.

**No data can be lost**, and that is measured rather than assumed: ``git log --all -S``
finds no assignment to any of the three in any commit, so every row is NULL by construction
in every deployed instance.

`SR#84` is why deleting beat wiring — a milestone is an item whose blockers are its
contents, so the dated thing is a task. `timezone` goes with the other two because its only
defensible meaning was the zone those dates were authored in; §6.5's chain is
explicit -> user -> workspace -> instance and has never had a project step.

**The downgrade is faithful in shape and empty in content.** It re-adds all three nullable
with the original types — ``UtcDateTime`` rather than the bare ``DATETIME`` autogenerate
reflected, because ``UtcDateTime`` is ``DateTime(timezone=True)`` and the difference is a
real one on PostgreSQL. There are no values to restore.

Revision ID: 653e220f5129
Revises: 8eb88cb06adc
Created: 2026-08-23 09:09:00.043805+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '653e220f5129'
down_revision: str | None = '8eb88cb06adc'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('start_at')
        batch_op.drop_column('due_at')
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('timezone', sqlalchemy.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sqlalchemy.Column('due_at', subroutine.db.types.UtcDateTime(), nullable=True))
        batch_op.add_column(sqlalchemy.Column('start_at', subroutine.db.types.UtcDateTime(), nullable=True))

    # ### end Alembic commands ###
