"""A long text an event carries is kept once

Item ``#578``, decision ``#4233``. ``event_text`` holds each long ``description`` or ``body`` an
event records, once per workspace, under its SHA-256, and an event carries ``{"sha256": …}`` in
its place from now on. Events already written keep their texts inline, and every reader takes
either.

**Going back writes each text back into the events that name it**, in the live table and the
archive, before the table goes, so the revision before reads every event whole.

Revision ID: 6c708db1582c
Revises: 340ff3f92fa6
Created: 2026-10-03 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

import sqlalchemy
from alembic import op

import subroutine.domain.events


revision: str = '6c708db1582c'
down_revision: str | None = '340ff3f92fa6'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade () -> None:
    """Make the table texts are kept in, empty."""

    op.create_table('event_text',
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('sha256', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('text', sqlalchemy.Text(), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_event_text_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('workspace_id', 'sha256', name=op.f('pk_event_text'))
    )


def downgrade () -> None:
    """Write every kept text back into the events that name it, then take the table away."""

    connection = op.get_bind()
    texts = sqlalchemy.table(
        'event_text',
        sqlalchemy.column('workspace_id', sqlalchemy.Uuid()),
        sqlalchemy.column('sha256', sqlalchemy.String()),
        sqlalchemy.column('text', sqlalchemy.Text()),
    )
    kept = {
        (row.workspace_id, row.sha256): row.text
        for row in connection.execute(sqlalchemy.select(texts))
    }

    for name in ('event', 'event_archive'):
        events = sqlalchemy.table(
            name,
            sqlalchemy.column('seq', sqlalchemy.BigInteger()),
            sqlalchemy.column('workspace_id', sqlalchemy.Uuid()),
            sqlalchemy.column('changes', sqlalchemy.JSON()),
        )
        naming = connection.execute(
            sqlalchemy.select(events.c.seq, events.c.workspace_id, events.c.changes).where(
                sqlalchemy.cast(events.c.changes, sqlalchemy.Text()).like('%"sha256"%')
            )
        ).all()

        for row in naming:
            mine = {digest: text for (space, digest), text in kept.items() if space == row.workspace_id}
            whole = subroutine.domain.events.restored(row.changes, mine.get)

            if whole != row.changes:
                connection.execute(
                    sqlalchemy.update(events).where(events.c.seq == row.seq).values(changes=whole)
                )

    op.drop_table('event_text')
