"""drop the vocabulary colour columns

`SR#523`, executing decision `SR#906` §7. `status.colour`, `item_type.colour` and
`tag.colour` were written by the seeder and read by nothing anywhere; `SR#1023` then
settled that colour carries the *project*, from a named palette resolved through the
settings registry, so a per-entry hex was both unread and the wrong shape.

**The downgrade is lossy and that is deliberate.** It re-adds the three columns nullable;
it does not restore the seeded values, because nothing is left that knows what they were.
Nothing ever read one, so no behaviour depends on them coming back.

Revision ID: 8eb88cb06adc
Revises: c9e4a1b73f52
Created: 2026-08-22 22:14:38.223572+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '8eb88cb06adc'
down_revision: str | None = 'c9e4a1b73f52'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_column('colour')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('colour')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('colour')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('colour', sqlalchemy.VARCHAR(length=16), nullable=True))

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('colour', sqlalchemy.VARCHAR(length=16), nullable=True))

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('colour', sqlalchemy.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
