"""an event is a kind of task

`SR#1236`, building decision `SR#1235`. An event — a birthday, a booked fortnight, a street
closed by the council, a code freeze — is *out of our control, never due or overdue; it just
happens*. It is stored as a task and told apart by its type's **category**, which is the column
``--ready`` and the agenda now read.

**Two steps, and the second is a seed rather than a schema change.** The CHECK on
``item_type.category`` widens to admit ``occasion``, and every workspace that already exists
gets the one row seed set 2 would have given it — because nothing re-seeds a workspace after it
is created, so a set added later reaches a live installation only from here.

**A workspace migrated by this stays at seed version 1 and has the row anyway.** The seeder is
idempotent by key: a later call finds ``event`` present, writes nothing and moves the number up.
Rewriting a JSON settings blob on two backends to say 2 would buy the same outcome for more risk.

**The literals are written out rather than imported**, which is `SR#1134`'s precedent one
revision along: a migration is a statement about one moment, and importing ``mixins`` would make
this one's behaviour change retroactively the day somebody edits a constant. The suite compares
what the two produce rather than trusting either.

Revision ID: 9c41d0b7ae52
Revises: 4f177421eb91
Created: 2026-08-25 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import datetime
import typing
import uuid

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = '9c41d0b7ae52'
down_revision: str | None = '4f177421eb91'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: What the column admitted before this, and after it. Written out for the reason above, and
#: because Alembic's autogenerate does not compare CHECK constraints at all — the vocabulary
#: lives in one, so an ``enum_check`` edit that only ever reached the models would pass the whole
#: suite and never reach a migrated database.
BEFORE = "'work', 'defect', 'question', 'decision', 'reference', 'record'"
AFTER = "'work', 'defect', 'question', 'occasion', 'decision', 'reference', 'record'"

#: Seed set 2, as one row. ``is_system`` because the installation ships it, and not
#: ``is_default`` because nothing files an event unless somebody asks for one.
EVENT = {'entity_type': 'task', 'key': 'event', 'label': 'Event', 'category': 'occasion'}

#: The space left between two seeded positions, so a workspace can insert its own between them
#: later. ``mixins.POSITION_GAP`` at the time of writing, copied deliberately.
POSITION_GAP = 1000

#: Enough of the table to write one row, declared here rather than reflected: a migration runs
#: against a schema the models may have moved past, and the UUID and datetime types have to be
#: the ones both backends store.
item_type = sqlalchemy.table(
    'item_type',
    sqlalchemy.column('id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('entity_type', sqlalchemy.String(length=16)),
    sqlalchemy.column('key', sqlalchemy.String(length=64)),
    sqlalchemy.column('label', sqlalchemy.String(length=128)),
    sqlalchemy.column('category', sqlalchemy.String(length=16)),
    sqlalchemy.column('position', sqlalchemy.Integer()),
    sqlalchemy.column('is_default', sqlalchemy.Boolean()),
    sqlalchemy.column('is_system', sqlalchemy.Boolean()),
    sqlalchemy.column('created_at', subroutine.db.types.UtcDateTime()),
    sqlalchemy.column('updated_at', subroutine.db.types.UtcDateTime()),
)

#: Enough of the referring table to ask whether anything is still typed as an event.
task = sqlalchemy.table(
    'task',
    sqlalchemy.column('type_id', subroutine.db.types.uuid_column()),
)


def upgrade () -> None:
    """Admit the new category, then give every existing workspace the type that uses it."""

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_item_type_category'), type_='check')
        batch_op.create_check_constraint('category', f'category IN ({AFTER})')

    connection = op.get_bind()

    # Where each workspace's task types have got to, so the new one goes after them rather
    # than on top of one. A workspace with no task types at all cannot happen — `init` seeds
    # five — but `or 0` is what stops this being a claim rather than a query.
    highest = dict(
        connection.execute(
            sqlalchemy.select(
                item_type.c.workspace_id, sqlalchemy.func.max(item_type.c.position)
            )
            .where(item_type.c.entity_type == 'task')
            .group_by(item_type.c.workspace_id)
        ).tuples().all()
    )

    already = set(
        connection.scalars(
            sqlalchemy.select(item_type.c.workspace_id).where(
                item_type.c.entity_type == 'task', item_type.c.key == EVENT['key']
            )
        )
    )

    now = datetime.datetime.now(datetime.UTC)

    rows = [
        {
            'id': uuid.uuid4(),
            'workspace_id': workspace_id,
            **EVENT,
            'position': (position or 0) + POSITION_GAP,
            'is_default': False,
            'is_system': True,
            'created_at': now,
            'updated_at': now,
        }
        for workspace_id, position in highest.items()
        if workspace_id not in already
    ]

    if rows:
        connection.execute(sqlalchemy.insert(item_type), rows)


def downgrade () -> None:
    """Refuse while anything is still an event, then take the type away and narrow the column.

    **This counts the rows itself, and an earlier version of it did not** (`SR#1689`). It said
    the delete came first and *may refuse*, on the grounds that ``task.type_id`` is
    ``ondelete=RESTRICT``. That is true on PostgreSQL and false on SQLite, which is the default
    backend and what ``init`` gives everybody: ``migrations/env.py`` turns SQLite's foreign-key
    enforcement off for the duration of a migration — which it must, because ``render_as_batch``
    rebuilds a table by copy-drop-rename — so the delete that PostgreSQL refuses, SQLite
    performs. Driven: one task typed ``event``, the downgrade succeeded, and the task was left
    pointing at a type that no longer existed.

    **Raised before the delete, because nothing here can be undone.** Measured rather than
    assumed: Alembic's ``begin_transaction`` is a no-op on SQLite, whose DDL is not transactional
    under Alembic's connection, and wrapping the run in a real transaction does not change it —
    the delete and the version bump both survive an exception. So a check made afterwards can
    report the damage and cannot reverse it, and refusing first is the only thing that leaves
    the database as it was.
    """

    connection = op.get_bind()

    types = list(
        connection.scalars(
            sqlalchemy.select(item_type.c.id).where(
                item_type.c.entity_type == 'task', item_type.c.key == EVENT['key']
            )
        )
    )

    typed = 0

    if types:
        typed = connection.scalar(
            sqlalchemy.select(sqlalchemy.func.count())
            .select_from(task)
            .where(task.c.type_id.in_(types))
        ) or 0

    if typed:
        raise RuntimeError(
            f"Cannot go back below this revision: {typed} task(s) are "
            f"'{EVENT['key']}'. Give those items another type first."
        )

    op.execute(
        item_type.delete().where(
            item_type.c.entity_type == 'task', item_type.c.key == EVENT['key']
        )
    )

    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_item_type_category'), type_='check')
        batch_op.create_check_constraint('category', f'category IN ({BEFORE})')
