"""a verification records the tree it ran against

`SR#1121`, and §14.5's evidence half. A durable, attributable, invalidatable record of what
was checked against a task — **never** a proof: an agent can post an exit code of zero without
running anything, and nothing built on this table may say otherwise.

**`tree_hash` is nullable, and that is a guard rather than a convenience** (Simon,
2026-08-23). ``NOT NULL`` is the natural way to write it and would make a record impossible
from a machine with no checkout, which §1.4 forbids: no §14 entity may be *required* in order
to do the ordinary thing. A record without one is still a record; it simply cannot expire.

**Nothing existing changes**, so this migration is additive and its downgrade is exact.
``LINK_ENTITY_TYPES`` has admitted ``verification`` since the initial migration, so a bug can
already derive from a failing check without any constraint moving.

Revision ID: a01dcd83a946
Revises: 653e220f5129
Created: 2026-08-23 16:43:28.015486+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'a01dcd83a946'
down_revision: str | None = '653e220f5129'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('task_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('passed', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('summary', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('output_excerpt', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('ran_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('tree_hash', sqlalchemy.String(length=64), nullable=True),
    sqlalchemy.Column('commit_sha', sqlalchemy.String(length=64), nullable=True),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('updated_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_verification_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_verification_task_id_task'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_verification_updated_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_verification_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_verification'))
    )
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_verification_workspace_id_task_id_ran_at', ['workspace_id', 'task_id', 'ran_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_workspace_id_task_id_ran_at')
        batch_op.drop_index(batch_op.f('ix_verification_workspace_id'))

    op.drop_table('verification')
    # ### end Alembic commands ###
