"""an events actor survives the row it points at

Revision ID: a1b3cef13c45
Revises: da7628199bff
Created: 2026-08-24 15:38:29.564706+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'a1b3cef13c45'
down_revision: str | None = 'da7628199bff'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


# The convention `db/base.py` sets, repeated here because a batch rebuild renders the table
# from reflection rather than from the metadata — so without it SQLite cannot name the
# constraints it is being asked to drop.
NAMING = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    """Stop an event's actor being erased by the deletion of the row it points at.

    Both columns were foreign keys with ``ON DELETE SET NULL``, so removing a user or a token
    silently rewrote every event that actor had ever written — retroactively, across the whole
    history, and with nothing recording that it used to say more. A GDPR erasure is a hard user
    delete by definition, and clearing out unused credentials is exactly the tidying nobody
    thinks of as destructive.

    The columns and their values are untouched; only the constraints go. Nothing joins through
    them — the model declares no relationship and every reader is a plain column read or an
    ``== id`` comparison — so what they added here was the clause that erased the answer.

    ``batch_alter_table`` because SQLite cannot ALTER a constraint at all. On PostgreSQL it
    emits the two ordinary ``ALTER TABLE`` statements; on SQLite it rebuilds the table by
    copy-drop-rename, which is safe here because ``event`` is a leaf — nothing holds a row
    pointing at it.
    """

    with op.batch_alter_table("event", naming_convention=NAMING) as batch:
        batch.drop_constraint("fk_event_actor_user_id_user", type_="foreignkey")
        batch.drop_constraint("fk_event_actor_token_id_api_token", type_="foreignkey")


def downgrade() -> None:
    """Put the constraints back, with the clause that made them a defect.

    Reversible only while nothing has been deleted: this restores the constraint, and a row
    whose actor no longer exists would refuse it. That is the honest shape — the information
    this migration protects cannot be un-protected once something has relied on it.
    """

    with op.batch_alter_table("event", naming_convention=NAMING) as batch:
        batch.create_foreign_key(
            "fk_event_actor_token_id_api_token",
            "api_token",
            ["actor_token_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_foreign_key(
            "fk_event_actor_user_id_user",
            "user",
            ["actor_user_id"],
            ["id"],
            ondelete="SET NULL",
        )
