"""Search is served by an index, on PostgreSQL

``q`` was ``ILIKE '%…%'``, which §10.4 names as one of the two predicates no index can
serve — so it scanned every row's prose, and the cost landed hardest on the search that
finds *nothing*, which is the duplicate check every agent runs before filing. Measured at
20,000 tasks: 119.30 ms scanning against 0.99 ms indexed.

**PostgreSQL only, and deliberately** (item ``#823``, design ``#871``). SQLite keeps the
scanning implementation: FTS5 is a virtual table, so keeping it in step needs triggers,
and §12.6b puts a SQLite database on local disk — one person's machine, which is the
scale the scan was measured adequate for. ``GET /v1/meta`` publishes which is in force.

**This is the first migration here that asks what it is running on.** Everything before
it describes one schema both backends build. A ``tsvector`` expression cannot exist on
SQLite at all — ``create_all`` there fails with ``no such function: to_tsvector`` — so
this has to branch, and on SQLite it correctly does nothing.

Nothing is rewritten and no data is touched: three ``CREATE INDEX`` statements, and a
downgrade that drops them. An instance that downgrades goes on answering ``q`` from the
scanning implementation, so this is reversible without loss.

Revision ID: a3f9c21d7e40
Revises: b1520dcd4afb
Created: 2026-08-14 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import subroutine.db.fulltext


revision: str = 'a3f9c21d7e40'
down_revision: str | None = 'b1520dcd4afb'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


# The indexes as the models declare them, rather than the SQL written out a second time.
# An expression index is used only when the query renders the same expression character
# for character, so a copy here that drifted from the models would produce an index that
# is built, maintained, and never consulted — with nothing failing.
INDEXES = ("ix_task_search", "ix_document_search", "ix_comment_search")


def _declared () -> list[typing.Any]:
    """Return the search indexes the models declare, in the order they are created."""

    import subroutine.db.models.activity
    import subroutine.db.models.work

    return [
        subroutine.db.models.work.ix_task_search,
        subroutine.db.models.work.ix_document_search,
        subroutine.db.models.activity.ix_comment_search,
    ]


def upgrade () -> None:
    """Create the full-text indexes where the database can have them."""

    if op.get_bind().dialect.name != "postgresql":
        return

    for index in _declared():
        index.create(op.get_bind())


def downgrade () -> None:
    """Drop them again, leaving ``q`` answered by the scanning implementation."""

    if op.get_bind().dialect.name != "postgresql":
        return

    for name in INDEXES:
        op.execute(f"DROP INDEX IF EXISTS {name}")
