"""token:admin is deleted from every role

Item ``#4568``, decision ``#4524``. ``token:admin`` was seeded into the owner and administrator
roles and checked nowhere, so the name goes from every role that holds it - the seeded ones and
any a workspace made - and nothing else changes: no role can do more or less than before.

**A credential's own scopes are left as they are.** One narrowed to ``token:admin`` alone could do
nothing, since nothing checked it, and taking the name out of its list would leave the list empty,
which means *not narrowed at all*. Left in, it goes on narrowing to nothing, and the name is
refused when a credential or a role is made, as any name this build does not know is.

**Going back puts it on every role holding ``user:admin``**, which is where the seed put it - the
owner and administrator roles. A role made by hand that held it without ``user:admin`` does not
get it back, since nothing records that it did; it gated nothing either way.

Revision ID: a5e890283615
Revises: 4b82edddbc80
Created: 2026-10-09 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

import sqlalchemy
from alembic import op


revision: str = 'a5e890283615'
down_revision: str | None = '4b82edddbc80'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: The name this deletes, and the one that says where the seed had put it.
RETIRED = 'token:admin'
ADMINISTERS_MEMBERSHIP = 'user:admin'

role = sqlalchemy.table(
    'role',
    sqlalchemy.column('id'),
    sqlalchemy.column('permissions', sqlalchemy.JSON()),
)


def _rewrite (change: typing.Callable[[list[str]], list[str]]) -> None:
    """Rewrite every role's permissions that ``change`` alters, and leave the rest unwritten."""

    connection = op.get_bind()

    for found in connection.execute(sqlalchemy.select(role.c.id, role.c.permissions)).all():
        held = list(found.permissions or [])
        wanted = change(held)

        if wanted != held:
            connection.execute(
                role.update().where(role.c.id == found.id).values(permissions=wanted)
            )


def upgrade () -> None:
    """Take ``token:admin`` out of every role that holds it."""

    _rewrite(lambda held: [one for one in held if one != RETIRED])


def downgrade () -> None:
    """Put ``token:admin`` back on every role holding ``user:admin``, in the order roles keep."""

    _rewrite(
        lambda held: sorted({*held, RETIRED}) if ADMINISTERS_MEMBERSHIP in held else held
    )
