"""an item says what superseded it

`SR#1688`, building decision `SR#1685`. Two rows per workspace, saying one thing from two
directions: a **link type** ``supersedes`` says *where the work went*, and a task **status**
``superseded`` says *not here any more*.

**Neither writes the other, and that is decided rather than unfinished.** `SR#84` settled the
same question for parents — a status inferred from a graph edge is a write nobody made, it
credits somebody with a decision they did not take, and it cannot reverse cleanly.

**No CHECK changes, unlike the seed migration before this one.** ``governing`` is already an
admitted link-type category and ``cancelled`` an admitted status category, so this is inserts
only. The status sits in ``cancelled`` deliberately: §10.7's invariant 5 ties ``completed_at``
to that category, and ``readiness.unblocked`` reads *finished* off that column — so a
superseded task stops blocking the successor that superseded it.

**A workspace migrated by this stays at its seed version and has the rows anyway**, exactly as
`SR#1236`'s migration left one at 1. The seeder is idempotent by key: a later call finds them
present, writes nothing and moves the number up.

**The literals are written out rather than imported**, which is `SR#1134`'s precedent: a
migration is a statement about one moment, and importing ``seed`` would make this file's
behaviour change retroactively the day somebody edits a constant. The suite compares what the
two produce rather than trusting either.

Revision ID: a986838fadc4
Revises: 9c41d0b7ae52
Created: 2026-08-30 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import datetime
import typing
import uuid

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'a986838fadc4'
down_revision: str | None = '9c41d0b7ae52'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: Seed set 3's task status. Not ``is_default``: nothing is filed as superseded.
STATUS = {
    'entity_type': 'task',
    'key': 'superseded',
    'label': 'Superseded',
    'category': 'cancelled',
}

#: Seed set 3's link type. ``is_system`` because the installation ships it, and
#: ``is_symmetric`` false because the two ends say different things.
LINK_TYPE = {
    'key': 'supersedes',
    'title': 'Supersedes',
    'inverse_title': 'Superseded by',
    'category': 'governing',
}

#: The space left between two seeded positions, so a workspace can insert its own between them
#: later. ``mixins.POSITION_GAP`` at the time of writing, copied deliberately.
POSITION_GAP = 1000

#: Enough of each table to write one row, declared here rather than reflected: a migration runs
#: against a schema the models may have moved past, and the UUID and datetime types have to be
#: the ones both backends store.
status = sqlalchemy.table(
    'status',
    sqlalchemy.column('id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('entity_type', sqlalchemy.String(length=16)),
    sqlalchemy.column('key', sqlalchemy.String(length=64)),
    sqlalchemy.column('label', sqlalchemy.String(length=128)),
    sqlalchemy.column('category', sqlalchemy.String(length=16)),
    sqlalchemy.column('position', sqlalchemy.Integer()),
    sqlalchemy.column('is_default', sqlalchemy.Boolean()),
    sqlalchemy.column('created_at', subroutine.db.types.UtcDateTime()),
    sqlalchemy.column('updated_at', subroutine.db.types.UtcDateTime()),
)

link_type = sqlalchemy.table(
    'link_type',
    sqlalchemy.column('id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('key', sqlalchemy.String(length=64)),
    sqlalchemy.column('title', sqlalchemy.String(length=128)),
    sqlalchemy.column('inverse_title', sqlalchemy.String(length=128)),
    sqlalchemy.column('category', sqlalchemy.String(length=16)),
    sqlalchemy.column('is_symmetric', sqlalchemy.Boolean()),
    sqlalchemy.column('is_system', sqlalchemy.Boolean()),
    sqlalchemy.column('created_at', subroutine.db.types.UtcDateTime()),
    sqlalchemy.column('updated_at', subroutine.db.types.UtcDateTime()),
)


def upgrade () -> None:
    """Give every existing workspace the status and the link type seed set 3 would have."""

    connection = op.get_bind()
    now = datetime.datetime.now(datetime.UTC)

    # Where each workspace's task statuses have got to, so the new one goes after them rather
    # than on top of one. A workspace with no task statuses cannot happen — `init` seeds six —
    # but `or 0` is what stops this being a claim rather than a query.
    highest = dict(
        connection.execute(
            sqlalchemy.select(status.c.workspace_id, sqlalchemy.func.max(status.c.position))
            .where(status.c.entity_type == 'task')
            .group_by(status.c.workspace_id)
        ).tuples().all()
    )

    holding = set(
        connection.scalars(
            sqlalchemy.select(status.c.workspace_id).where(
                status.c.entity_type == 'task', status.c.key == STATUS['key']
            )
        )
    )

    rows = [
        {
            'id': uuid.uuid4(),
            'workspace_id': workspace_id,
            **STATUS,
            'position': (position or 0) + POSITION_GAP,
            'is_default': False,
            'created_at': now,
            'updated_at': now,
        }
        for workspace_id, position in highest.items()
        if workspace_id not in holding
    ]

    if rows:
        connection.execute(sqlalchemy.insert(status), rows)

    # **Every workspace, read from the status table rather than from `workspace`.** A link type
    # is not scoped by entity type, so there is no per-kind maximum to find and nothing to
    # order against — `link_type` carries no position column.
    everywhere = set(connection.scalars(sqlalchemy.select(status.c.workspace_id).distinct()))

    already = set(
        connection.scalars(
            sqlalchemy.select(link_type.c.workspace_id).where(
                link_type.c.key == LINK_TYPE['key']
            )
        )
    )

    edges = [
        {
            'id': uuid.uuid4(),
            'workspace_id': workspace_id,
            **LINK_TYPE,
            'is_symmetric': False,
            'is_system': True,
            'created_at': now,
            'updated_at': now,
        }
        for workspace_id in sorted(everywhere - already)
    ]

    if edges:
        connection.execute(sqlalchemy.insert(link_type), edges)


#: Enough of the two referring tables to ask whether anything is using the rows below.
task = sqlalchemy.table(
    'task',
    sqlalchemy.column('status_id', subroutine.db.types.uuid_column()),
)

link = sqlalchemy.table(
    'link',
    sqlalchemy.column('link_type_id', subroutine.db.types.uuid_column()),
)


def _still_in_use (connection: typing.Any, referring: typing.Any, column: typing.Any,
                   ids: typing.Sequence[uuid.UUID]) -> int:
    """Return how many rows still point at any of these vocabulary rows."""

    if not ids:
        return 0

    return connection.scalar(
        sqlalchemy.select(sqlalchemy.func.count())
        .select_from(referring)
        .where(column.in_(ids))
    ) or 0


def downgrade () -> None:
    """Take both rows away, refusing while anything still points at them.

    **The check is written out because the foreign key cannot be relied on here, and that was
    measured rather than assumed.** Both ``task.status_id`` and ``link.link_type_id`` declare
    ``ondelete=RESTRICT``, and ``migrations/env.py`` turns SQLite's foreign-key enforcement
    **off for the duration of a migration** — which it must, because ``render_as_batch``
    rebuilds a table by copy-drop-rename. So the delete that PostgreSQL refuses, SQLite
    performs, leaving a task pointing at a status that no longer exists.

    Driving this file's own downgrade is what found it: one task marked superseded, one link
    drawn, and the downgrade succeeded on SQLite with a dangling foreign key behind it. The
    already-shipped ``9c41d0b7ae52`` asserts the same refusal and has the same hole; that is
    `SR#1689`.

    **Raised rather than logged, and before either delete**, so a database that cannot go back
    is left exactly as it was rather than half-emptied.
    """

    connection = op.get_bind()

    types = list(
        connection.scalars(
            sqlalchemy.select(link_type.c.id).where(link_type.c.key == LINK_TYPE['key'])
        )
    )
    statuses = list(
        connection.scalars(
            sqlalchemy.select(status.c.id).where(
                status.c.entity_type == 'task', status.c.key == STATUS['key']
            )
        )
    )

    linked = _still_in_use(connection, link, link.c.link_type_id, types)
    marked = _still_in_use(connection, task, task.c.status_id, statuses)

    if linked or marked:
        raise RuntimeError(
            f"Cannot go back below this revision: {linked} link(s) use "
            f"'{LINK_TYPE['key']}' and {marked} task(s) are '{STATUS['key']}'. "
            f"Remove those links and give those tasks another status first."
        )

    op.execute(link_type.delete().where(link_type.c.key == LINK_TYPE['key']))
    op.execute(
        status.delete().where(
            status.c.entity_type == 'task', status.c.key == STATUS['key']
        )
    )
