"""An event is indexed by when it happened

Every other index on this table is keyed on ``seq``, because every other reader pages
through the feed rather than asking about a period. ``touched_at`` (item ``#815``,
decision ``#817``) is the first question about *when*, and ``seq`` only correlates with
time — it does not answer it. Without this the ``EXISTS`` behind it scans a workspace's
whole history once per candidate row.

Revision ID: b1520dcd4afb
Revises: ce11c7d2df2f
Created: 2026-08-11 19:14:18.995062+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'b1520dcd4afb'
down_revision: str | None = 'ce11c7d2df2f'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_workspace_id_created_at')

    # ### end Alembic commands ###
