"""a project key is unique among siblings

Revision ID: b6a0e7c14d92
Revises: c7d419e6a2b8
Created: 2026-08-17 09:41:07.113204

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'b6a0e7c14d92'
down_revision: str | None = 'c7d419e6a2b8'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # **Widening, so nothing existing can violate it.** Every key that was unique in its
    # workspace is unique among its siblings as well, so this runs on any installation
    # without looking at the rows. The downgrade is the direction that has to check.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('uq_project_workspace_id_key', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.create_index('uq_project_workspace_id_parent_id_key', ['workspace_id', 'parent_id', 'key'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NOT NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NOT NULL'))
        batch_op.create_index('uq_project_workspace_id_key_at_root', ['workspace_id', 'key'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # **The older schema cannot hold what this one allows** — the shape migration
    # `ea3e86ad12c4` met one table along. Two live projects may now share a key under
    # different parents, and the plain workspace-wide index below cannot accept them, so
    # the downgrade would die on an integrity error naming a constraint rather than the
    # data. Refused by name instead, saying which key and what to do about it.
    duplicates = op.get_bind().execute(
        sqlalchemy.text(
            "SELECT key FROM project WHERE deleted_at IS NULL "
            "GROUP BY workspace_id, key HAVING COUNT(*) > 1 ORDER BY key"
        )
    ).scalars().all()

    if duplicates:
        raise RuntimeError(
            f"This installation has more than one project keyed each of "
            f"{', '.join(repr(key) for key in duplicates)} in one workspace — which the "
            f"schema before this migration cannot represent, because it made every key "
            f"unique across the workspace rather than among its siblings. Rename them, and "
            f"run this again."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('uq_project_workspace_id_key_at_root', sqlite_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NULL'))
        batch_op.drop_index('uq_project_workspace_id_parent_id_key', sqlite_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NOT NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL AND parent_id IS NOT NULL'))
        batch_op.create_index('uq_project_workspace_id_key', ['workspace_id', 'key'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    # ### end Alembic commands ###
