"""a spike is a question

Revision ID: c3a7f21b9d40
Revises: 1f61c97bf2ca
Created: 2026-09-10 08:05:00.000000

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy


revision: str = 'c3a7f21b9d40'
down_revision: str | None = '1f61c97bf2ca'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


#: Renaming the row in place rather than adding one and moving every task onto it.
#:
#: **Nothing about a task changes**, which is the whole reason this shape was chosen: the type
#: is referenced by `task.type_id`, and the row keeps its id, so no item is rewritten, no event
#: is emitted and no version moves. Adding a `question` row and repointing every task would
#: have touched 97 rows on the instance this was written on to achieve the same end state.
#:
#: **Seed sets could not have done it.** `_seed_item_types` skips a key it already finds, so a
#: set can add and can never rename or retire — which is correct for a mechanism that runs
#: repeatedly, and is why this is migration work.
#:
#: **The `workspace_id NOT IN` guard is for a collision that cannot happen yet.** Item types are
#: not curatable — `api/vocabulary.py` deliberately publishes no endpoint for them — so the only
#: `question` rows in existence are ones this migration or the new seed wrote. The unique
#: constraint is on `(workspace_id, entity_type, key)`, and the failure would be an
#: `IntegrityError` in the middle of somebody's upgrade, so it is worth one clause to make the
#: second run of this a no-op instead.
_RENAME = sqlalchemy.text(
    """
    UPDATE item_type
       SET key = :to_key, label = :to_label
     WHERE entity_type = 'task'
       AND key = :from_key
       AND workspace_id NOT IN (
           SELECT workspace_id FROM item_type
            WHERE entity_type = 'task' AND key = :to_key
       )
    """
)


def upgrade() -> None:
    """Rename every workspace's `spike` type to `question`.

    Decision `SR#2390`: `spike` is agile jargon and unfamiliar outside it, where `question` is
    the plainest word available and is already the name of the category the type sits under.
    """

    op.get_bind().execute(
        _RENAME, {"from_key": "spike", "to_key": "question", "to_label": "Question"}
    )


def downgrade() -> None:
    """Put the old word back.

    **Reversible, unlike most of this project's migrations**, because nothing is dropped: the
    row is the same row and the tasks pointing at it never moved. A workspace seeded *after* the
    rename is renamed back too, which is what going back to the old vocabulary means.
    """

    op.get_bind().execute(
        _RENAME, {"from_key": "question", "to_key": "spike", "to_label": "Spike"}
    )
