"""What brings the next occurrence into being, beside what its date is measured from

``recurrence_anchor`` says where the next date falls — the rule's grid, or the instant the
last one was finished. It does **not** say whether an occurrence is waiting for you at all,
and those are different questions that were folded into one until decision ``#915``. Item
``#94``.

- ``completion`` materialises one occurrence ahead, because work you have to do needs
  somewhere to be finished.
- ``time`` materialises none. A birthday is not a to-do and nobody ever closes one, so the
  series lives on the calendar and an occurrence becomes a row only when somebody acts on it.

Three of the four combinations mean something; ``time`` with a ``completion`` anchor does
not, because with nothing ever completed there is no instant for that anchor to measure
from. **That pair is refused in the service layer rather than here**: a CHECK constraint is
not input validation in this project — it arrives as a driver error naming no field, and on
SQLite it may not fire at all.

Nullable, so every task in existence is unchanged and a row with no rule keeps saying
nothing about how it repeats. Nothing is backfilled: no installation can have a recurrence
yet, because until ``#94`` nothing wrote one.

Revision ID: c7d419e6a2b8
Revises: f2b8c1a94d63
Created: 2026-08-15 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

import sqlalchemy
from alembic import op


revision: str = 'c7d419e6a2b8'
down_revision: str | None = 'f2b8c1a94d63'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade () -> None:
    """Add the trigger and the vocabulary it is held to."""

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column('recurrence_trigger', sqlalchemy.String(length=16), nullable=True)
        )
        batch_op.create_check_constraint(
            'recurrence_trigger',
            "recurrence_trigger IS NULL OR recurrence_trigger IN ('completion', 'time')",
        )


def downgrade () -> None:
    """Take it back out. Nothing else reads it, so nothing else has to move."""

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_task_recurrence_trigger'), type_='check')
        batch_op.drop_column('recurrence_trigger')
