"""a project key is lower case

Revision ID: c858f2942244
Revises: 243497ffc330
Created: 2026-08-05 15:40:18.831666+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.

**The data change is not optional and autogenerate did not find it** (item ``#508``). Every
lookup compares ``projects.normalize_key(what the caller typed)`` against the stored
``project.key`` — one function, deliberately, so both transports resolve ``sr`` to the same
project. That function now lower-cases, so an instance whose keys are still upper-cased would
match nothing: ``--project SR`` and ``+SR`` would both report that no such project exists,
which reads as data loss rather than as an upgrade.

Widened first and rewritten second. The widening is what makes room for the hyphenated
compounds the same item allows — ``service-marketing`` is seventeen characters against the
old ceiling of sixteen.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'c858f2942244'
down_revision: str | None = '243497ffc330'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sqlalchemy.VARCHAR(length=16),
               type_=sqlalchemy.String(length=32),
               existing_nullable=False)

    # `lower()` rather than anything backend-specific: it is standard SQL and this project
    # runs on both. Unconditional, because a key that is already lower-cased is unchanged by
    # it and a WHERE clause here would only be a slower way to say the same thing.
    op.execute(sqlalchemy.text("UPDATE project SET key = lower(key)"))


def downgrade() -> None:
    """Undo this migration.

    **Lossy in two ways, and both are stated rather than discovered.** A key of more than
    sixteen characters cannot fit the old column, so a downgrade after somebody has used a
    long hyphenated key will fail on the narrowing — which is the right way round, since
    truncating an address silently would be worse. And upper-casing cannot restore a key that
    was *created* lower-cased, because there was never an upper-case form of it to return to.
    """
    op.execute(sqlalchemy.text("UPDATE project SET key = upper(key)"))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sqlalchemy.String(length=32),
               type_=sqlalchemy.VARCHAR(length=16),
               existing_nullable=False)
