"""A search ranks a title match above a body match

The indexed expression joined a row's columns into one string, so ranking was term
frequency and density alone: a long body mentioning a word repeatedly outranked a
title that was *about* it. Measured on this project's own instance — searching for
``seeded`` put the item titled *A search for 'seeded' finds 'seed'* **fifth**, below
three body matches and a 97 KB specification (item ``#624``).

Each column is now its own ``to_tsvector``, labelled ``A`` for the title and ``B`` for
the prose under it and concatenated. ``ts_rank``'s default weights make a title match
worth two and a half times a body match, so no query has to say anything.

**Which rows match does not change.** ``@@`` ignores weights entirely, so the same
search finds the same items; only their order moves. Nothing is rewritten and no data
is touched — the indexes are dropped and rebuilt, which is a rewrite of the index
alone.

**PostgreSQL only**, like the migration that created them (``a3f9c21d7e40``, design
``#871``). SQLite keeps the scanning implementation, which never ranked at all, so
there is nothing here for it to do.

Revision ID: c9e4a1b73f52
Revises: 3a3d6accc196
Created: 2026-08-20 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import subroutine.db.fulltext


revision: str = 'c9e4a1b73f52'
down_revision: str | None = '3a3d6accc196'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def _declared () -> list[typing.Any]:
    """Return the search indexes the models declare, in the order they are created.

    Read from the models rather than written out here, for the reason ``a3f9c21d7e40``
    gives at length: an expression index is used only when the query renders the same
    expression character for character, so a copy that drifted would produce an index
    that is built, maintained and never consulted — with nothing failing.
    """

    import subroutine.db.models.activity
    import subroutine.db.models.work

    return [
        subroutine.db.models.work.ix_task_search,
        subroutine.db.models.work.ix_document_search,
        subroutine.db.models.activity.ix_comment_search,
    ]


def upgrade () -> None:
    """Rebuild the full-text indexes over the weighted expression."""

    if op.get_bind().dialect.name != "postgresql":
        return

    for index in _declared():
        op.execute(f"DROP INDEX IF EXISTS {index.name}")
        index.create(op.get_bind())


def downgrade () -> None:
    """Drop them.

    **Not rebuilt over the old expression**, and that is deliberate rather than lazy: the
    unweighted form is gone from the models, so recreating it would mean a second copy of
    an expression here — the exact thing the note above refuses. An instance that
    downgrades answers ``q`` from the scanning implementation, unranked, which is what it
    did before ``a3f9c21d7e40`` and is reversible without loss.
    """

    if op.get_bind().dialect.name != "postgresql":
        return

    for index in _declared():
        op.execute(f"DROP INDEX IF EXISTS {index.name}")
