"""a browser holds a session

Revision ID: ce11c7d2df2f
Revises: c858f2942244
Created: 2026-08-08 08:04:25.014642+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'ce11c7d2df2f'
down_revision: str | None = 'c858f2942244'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_link',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('user_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('token_prefix', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('token_hash', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('expires_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('redeemed_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_login_link_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_login_link_user_id_user'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_login_link'))
    )
    with op.batch_alter_table('login_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_link_token_prefix'), ['token_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_link_user_id'), ['user_id'], unique=False)

    op.create_table('web_session',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('user_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('token_prefix', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('token_hash', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('expires_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('last_used_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('revoked_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('login_link_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['login_link_id'], ['login_link.id'], name=op.f('fk_web_session_login_link_id_login_link'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_web_session_user_id_user'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_web_session'))
    )
    with op.batch_alter_table('web_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_session_token_prefix'), ['token_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_web_session_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_web_session_token_prefix'))

    op.drop_table('web_session')
    with op.batch_alter_table('login_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_link_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_link_token_prefix'))

    op.drop_table('login_link')
    # ### end Alembic commands ###
