"""a saved view is a query and an arrangement

Revision ID: cfeea5d4dd35
Revises: c3a7f21b9d40
Created: 2026-09-21 09:38:43.395728+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'cfeea5d4dd35'
down_revision: str | None = 'c3a7f21b9d40'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    op.create_table('saved_view',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('key', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('q', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('arrangement', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('order', sqlalchemy.String(length=64), nullable=True),
    sqlalchemy.Column('group_by', sqlalchemy.String(length=32), nullable=True),
    sqlalchemy.Column('owner_id', sqlalchemy.Uuid(), nullable=False),
    # `sqlalchemy.false()` rather than the `text('0')` autogenerate wrote: PostgreSQL
    # refuses an integer default on a boolean column by name, and this migration is
    # generated on SQLite, where it is accepted. `f2b8c1a94d63` is the precedent.
    sqlalchemy.Column(
    'shared', sqlalchemy.Boolean(), server_default=sqlalchemy.false(), nullable=False
    ),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.CheckConstraint("arrangement IN ('agenda', 'list', 'board')", name=op.f('ck_saved_view_arrangement')),
    sqlalchemy.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_saved_view_owner_id_user'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_saved_view_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_saved_view')),
    sqlalchemy.UniqueConstraint('workspace_id', 'key', name='uq_saved_view_workspace_id_key')
    )
    with op.batch_alter_table('saved_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_view_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_view_workspace_id'), ['workspace_id'], unique=False)



def downgrade() -> None:
    """Undo this migration."""
    with op.batch_alter_table('saved_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_view_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_saved_view_owner_id'))

    op.drop_table('saved_view')
