"""token write scope

Revision ID: d5d0458f5ad5
Revises: e4862f5da622
Created: 2026-08-03 15:05:47.024083+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'd5d0458f5ad5'
down_revision: str | None = 'e4862f5da622'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('project_write_scope', sqlalchemy.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_column('project_write_scope')

    # ### end Alembic commands ###
