"""initial schema

Revision ID: da1d7a5b1960
Revises: 
Created: 2026-07-28 19:21:48.365553+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'da1d7a5b1960'
down_revision: str | None = None
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('username', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('username_normalized', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('email', sqlalchemy.String(length=320), nullable=True),
    sqlalchemy.Column('email_normalized', sqlalchemy.String(length=320), nullable=True),
    sqlalchemy.Column('display_name', sqlalchemy.String(length=255), nullable=True),
    sqlalchemy.Column('password_hash', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('is_service_account', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('is_superuser', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('is_active', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('timezone', sqlalchemy.String(length=64), nullable=True),
    sqlalchemy.Column('last_login_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('uq_user_email_normalized', ['email_normalized'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.create_index('uq_user_username_normalized', ['username_normalized'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    op.create_table('workspace',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('slug', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=255), nullable=False),
    sqlalchemy.Column('description', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('timezone', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('settings', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_workspace')),
    sqlalchemy.UniqueConstraint('slug', name=op.f('uq_workspace_slug'))
    )
    op.create_table('api_token',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('user_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('title', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('token_prefix', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('token_hash', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('scopes', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('project_scope', sqlalchemy.JSON(), nullable=True),
    sqlalchemy.Column('expires_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('last_used_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('revoked_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_api_token_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_api_token_user_id_user'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_api_token_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_api_token'))
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_token_prefix'), ['token_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_token_user_id'), ['user_id'], unique=False)

    op.create_table('comment',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('entity_type', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('entity_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('parent_comment_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('author_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('body', sqlalchemy.Text(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.CheckConstraint("entity_type IN ('task', 'project', 'document')", name=op.f('ck_comment_ck_comment_entity_type')),
    sqlalchemy.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_comment_author_id_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], name=op.f('fk_comment_parent_comment_id_comment'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_comment_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_comment_workspace_id_entity_type_entity_id_created_at', ['workspace_id', 'entity_type', 'entity_id', 'created_at'], unique=False)

    op.create_table('item_type',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('entity_type', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('key', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('label', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('colour', sqlalchemy.String(length=16), nullable=True),
    sqlalchemy.Column('position', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('is_default', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('is_system', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.CheckConstraint("entity_type IN ('task', 'document')", name=op.f('ck_item_type_ck_item_type_entity_type')),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_item_type_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_item_type')),
    sqlalchemy.UniqueConstraint('workspace_id', 'entity_type', 'key', name='uq_item_type_workspace_id_entity_type_key')
    )
    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_type_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('link_type',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('key', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('inverse_title', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('is_symmetric', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('is_system', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_link_type_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_link_type')),
    sqlalchemy.UniqueConstraint('workspace_id', 'key', name='uq_link_type_workspace_id_key')
    )
    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_type_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('role',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('key', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('description', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('permissions', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('is_system', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_role_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sqlalchemy.UniqueConstraint('workspace_id', 'key', name='uq_role_workspace_id_key')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('status',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('entity_type', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('key', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('label', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('category', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('colour', sqlalchemy.String(length=16), nullable=True),
    sqlalchemy.Column('position', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('is_default', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.CheckConstraint("category IN ('todo', 'in_progress', 'done', 'cancelled', 'draft', 'current', 'superseded', 'archived')", name=op.f('ck_status_ck_status_category')),
    sqlalchemy.CheckConstraint("entity_type IN ('task', 'project', 'document')", name=op.f('ck_status_ck_status_entity_type')),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_status_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_status')),
    sqlalchemy.UniqueConstraint('workspace_id', 'entity_type', 'key', name='uq_status_workspace_id_entity_type_key')
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('tag',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('name', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('name_normalized', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('colour', sqlalchemy.String(length=16), nullable=True),
    sqlalchemy.Column('description', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_tag_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sqlalchemy.UniqueConstraint('workspace_id', 'name_normalized', name='uq_tag_workspace_id_name_normalized')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('event',
    sqlalchemy.Column('seq', sqlalchemy.BigInteger().with_variant(sqlalchemy.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('actor_user_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('actor_token_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('entity_type', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('entity_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('action', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('changes', sqlalchemy.JSON(), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['actor_token_id'], ['api_token.id'], name=op.f('fk_event_actor_token_id_api_token'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_event_actor_user_id_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_event_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('seq', name=op.f('pk_event')),
    sqlalchemy.UniqueConstraint('id', name=op.f('uq_event_id'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_event_workspace_id_entity_type_entity_id_seq', ['workspace_id', 'entity_type', 'entity_id', 'seq'], unique=False)
        batch_op.create_index('ix_event_workspace_id_seq', ['workspace_id', 'seq'], unique=False)

    op.create_table('link',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('source_type', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('source_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('target_type', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('target_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('link_type_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.CheckConstraint("source_type IN ('task', 'document', 'verification')", name=op.f('ck_link_ck_link_source_type')),
    sqlalchemy.CheckConstraint("target_type IN ('task', 'document', 'verification')", name=op.f('ck_link_ck_link_target_type')),
    sqlalchemy.CheckConstraint('NOT (source_type = target_type AND source_id = target_id)', name=op.f('ck_link_ck_link_not_self')),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_link_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['link_type_id'], ['link_type.id'], name=op.f('fk_link_link_type_id_link_type'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_link_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_link'))
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_link_workspace_id_source_type_source_id', ['workspace_id', 'source_type', 'source_id'], unique=False)
        batch_op.create_index('ix_link_workspace_id_target_type_target_id', ['workspace_id', 'target_type', 'target_id'], unique=False)
        batch_op.create_index('uq_link_source_target_type', ['source_type', 'source_id', 'target_type', 'target_id', 'link_type_id'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    op.create_table('project',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('parent_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('visibility', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('key', sqlalchemy.String(length=16), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=512), nullable=False),
    sqlalchemy.Column('description', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('status_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('owner_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('is_inbox', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('template', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('settings', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('path', sqlalchemy.String(length=1024), nullable=False),
    sqlalchemy.Column('depth', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('position', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('start_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('due_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('timezone', sqlalchemy.String(length=64), nullable=True),
    sqlalchemy.Column('next_ref_number', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('archived_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('metadata', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('updated_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.CheckConstraint("visibility IN ('public', 'private')", name=op.f('ck_project_ck_project_visibility')),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_project_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_project_owner_id_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['parent_id'], ['project.id'], name=op.f('fk_project_parent_id_project'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_project_status_id_status'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_project_updated_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_project_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_project_workspace_id_parent_id', ['workspace_id', 'parent_id'], unique=False)
        batch_op.create_index('ix_project_workspace_id_path', ['workspace_id', 'path'], unique=False)
        batch_op.create_index('ix_project_workspace_id_status_id', ['workspace_id', 'status_id'], unique=False)
        batch_op.create_index('uq_project_workspace_id_key', ['workspace_id', 'key'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    op.create_table('workspace_member',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('user_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('role_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_workspace_member_role_id_role'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_workspace_member_user_id_user'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_workspace_member_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_workspace_member')),
    sqlalchemy.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_workspace_id_user_id')
    )
    with op.batch_alter_table('workspace_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_member_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_member_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('document',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('project_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('parent_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('type_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('ref', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('number', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('origin_project_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=512), nullable=False),
    sqlalchemy.Column('body', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('status_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('owner_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('supersedes_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('path', sqlalchemy.String(length=1024), nullable=False),
    sqlalchemy.Column('depth', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('position', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('archived_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('metadata', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('content_updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('updated_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_document_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['origin_project_id'], ['project.id'], name=op.f('fk_document_origin_project_id_project'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_document_owner_id_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['parent_id'], ['document.id'], name=op.f('fk_document_parent_id_document'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_document_project_id_project'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_document_status_id_status'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['supersedes_id'], ['document.id'], name=op.f('fk_document_supersedes_id_document'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['type_id'], ['item_type.id'], name=op.f('fk_document_type_id_item_type'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_document_updated_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_document_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sqlalchemy.UniqueConstraint('origin_project_id', 'number', name='uq_document_origin_project_id_number')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_document_workspace_id_path', ['workspace_id', 'path'], unique=False)
        batch_op.create_index('ix_document_workspace_id_project_id_status_id', ['workspace_id', 'project_id', 'status_id'], unique=False)
        batch_op.create_index('ix_document_workspace_id_type_id', ['workspace_id', 'type_id'], unique=False)
        batch_op.create_index('uq_document_supersedes_id', ['supersedes_id'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.create_index('uq_document_workspace_id_ref', ['workspace_id', 'ref'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    op.create_table('project_member',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('project_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('user_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('role_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_project_member_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_member_project_id_project'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_project_member_role_id_role'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_project_member_user_id_user'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_project_member_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_project_member')),
    sqlalchemy.UniqueConstraint('project_id', 'user_id', name='uq_project_member_project_id_user_id')
    )
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_member_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_member_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('task',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('project_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('parent_task_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('type_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('ref', sqlalchemy.String(length=64), nullable=False),
    sqlalchemy.Column('number', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('origin_project_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('title', sqlalchemy.String(length=512), nullable=False),
    sqlalchemy.Column('description', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('status_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('importance', sqlalchemy.SmallInteger(), nullable=True),
    sqlalchemy.Column('urgency', sqlalchemy.SmallInteger(), nullable=True),
    sqlalchemy.Column('due_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('due_is_all_day', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('planned_for', subroutine.db.types.CalendarDate(), nullable=True),
    sqlalchemy.Column('start_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('start_is_all_day', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('timezone', sqlalchemy.String(length=64), nullable=True),
    sqlalchemy.Column('estimate_minutes', sqlalchemy.Integer(), nullable=True),
    sqlalchemy.Column('spent_minutes', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('assignee_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('recurrence_rule', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('recurrence_anchor', sqlalchemy.String(length=16), nullable=True),
    sqlalchemy.Column('recurrence_text', sqlalchemy.Text(), nullable=True),
    sqlalchemy.Column('recurrence_template_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('occurrence_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('is_template', sqlalchemy.Boolean(), nullable=False),
    sqlalchemy.Column('path', sqlalchemy.String(length=1024), nullable=False),
    sqlalchemy.Column('depth', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('position', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('completed_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('archived_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('metadata', sqlalchemy.JSON(), nullable=False),
    sqlalchemy.Column('content_updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('created_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('updated_by', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('version', sqlalchemy.Integer(), nullable=False),
    sqlalchemy.Column('deleted_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.CheckConstraint("recurrence_anchor IS NULL OR recurrence_anchor IN ('schedule', 'completion')", name=op.f('ck_task_ck_task_recurrence_anchor')),
    sqlalchemy.CheckConstraint('importance IS NULL OR (importance BETWEEN 1 AND 5)', name=op.f('ck_task_ck_task_importance_range')),
    sqlalchemy.CheckConstraint('urgency IS NULL OR (urgency BETWEEN 1 AND 5)', name=op.f('ck_task_ck_task_urgency_range')),
    sqlalchemy.ForeignKeyConstraint(['assignee_id'], ['user.id'], name=op.f('fk_task_assignee_id_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_task_created_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['origin_project_id'], ['project.id'], name=op.f('fk_task_origin_project_id_project'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['parent_task_id'], ['task.id'], name=op.f('fk_task_parent_task_id_task'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_project_id_project'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['recurrence_template_id'], ['task.id'], name=op.f('fk_task_recurrence_template_id_task'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_task_status_id_status'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['type_id'], ['item_type.id'], name=op.f('fk_task_type_id_item_type'), ondelete='RESTRICT'),
    sqlalchemy.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_task_updated_by_user'), ondelete='SET NULL'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_task_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    sqlalchemy.UniqueConstraint('origin_project_id', 'number', name='uq_task_origin_project_id_number')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_recurrence_template_id'), ['recurrence_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_task_workspace_id_assignee_id_status_id', ['workspace_id', 'assignee_id', 'status_id'], unique=False)
        batch_op.create_index('ix_task_workspace_id_due_at', ['workspace_id', 'due_at'], unique=False)
        batch_op.create_index('ix_task_workspace_id_path', ['workspace_id', 'path'], unique=False)
        batch_op.create_index('ix_task_workspace_id_planned_for', ['workspace_id', 'planned_for'], unique=False)
        batch_op.create_index('ix_task_workspace_id_project_id_status_id', ['workspace_id', 'project_id', 'status_id'], unique=False)
        batch_op.create_index('ix_task_workspace_id_updated_at', ['workspace_id', 'updated_at'], unique=False)
        batch_op.create_index('uq_task_workspace_id_ref', ['workspace_id', 'ref'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    op.create_table('document_tag',
    sqlalchemy.Column('document_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('tag_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_tag_document_id_document'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_document_tag_tag_id_tag'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('document_id', 'tag_id', name=op.f('pk_document_tag'))
    )
    with op.batch_alter_table('document_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_tag_tag_id'), ['tag_id'], unique=False)

    op.create_table('task_tag',
    sqlalchemy.Column('task_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('tag_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_task_tag_tag_id_tag'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_tag_task_id_task'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('pk_task_tag'))
    )
    with op.batch_alter_table('task_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_tag_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_tag_tag_id'))

    op.drop_table('task_tag')
    with op.batch_alter_table('document_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_tag_tag_id'))

    op.drop_table('document_tag')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('uq_task_workspace_id_ref', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_index('ix_task_workspace_id_updated_at')
        batch_op.drop_index('ix_task_workspace_id_project_id_status_id')
        batch_op.drop_index('ix_task_workspace_id_planned_for')
        batch_op.drop_index('ix_task_workspace_id_path')
        batch_op.drop_index('ix_task_workspace_id_due_at')
        batch_op.drop_index('ix_task_workspace_id_assignee_id_status_id')
        batch_op.drop_index(batch_op.f('ix_task_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_task_recurrence_template_id'))
        batch_op.drop_index(batch_op.f('ix_task_parent_task_id'))

    op.drop_table('task')
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_member_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_project_member_user_id'))

    op.drop_table('project_member')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('uq_document_workspace_id_ref', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_index('uq_document_supersedes_id', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_index('ix_document_workspace_id_type_id')
        batch_op.drop_index('ix_document_workspace_id_project_id_status_id')
        batch_op.drop_index('ix_document_workspace_id_path')
        batch_op.drop_index(batch_op.f('ix_document_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_document_parent_id'))

    op.drop_table('document')
    with op.batch_alter_table('workspace_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_member_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_member_user_id'))

    op.drop_table('workspace_member')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('uq_project_workspace_id_key', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_index('ix_project_workspace_id_status_id')
        batch_op.drop_index('ix_project_workspace_id_path')
        batch_op.drop_index('ix_project_workspace_id_parent_id')
        batch_op.drop_index(batch_op.f('ix_project_workspace_id'))

    op.drop_table('project')
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index('uq_link_source_target_type', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_index('ix_link_workspace_id_target_type_target_id')
        batch_op.drop_index('ix_link_workspace_id_source_type_source_id')
        batch_op.drop_index(batch_op.f('ix_link_workspace_id'))

    op.drop_table('link')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_workspace_id_seq')
        batch_op.drop_index('ix_event_workspace_id_entity_type_entity_id_seq')
        batch_op.drop_index(batch_op.f('ix_event_workspace_id'))

    op.drop_table('event')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_workspace_id'))

    op.drop_table('tag')
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_workspace_id'))

    op.drop_table('status')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_workspace_id'))

    op.drop_table('role')
    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_type_workspace_id'))

    op.drop_table('link_type')
    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_type_workspace_id'))

    op.drop_table('item_type')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_workspace_id_entity_type_entity_id_created_at')
        batch_op.drop_index(batch_op.f('ix_comment_workspace_id'))

    op.drop_table('comment')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_token_token_prefix'))

    op.drop_table('api_token')
    op.drop_table('workspace')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('uq_user_username_normalized', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.drop_index('uq_user_email_normalized', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    op.drop_table('user')
    # ### end Alembic commands ###
