"""a link type says what it does

`SR#1154` and `SR#1156`, building decision `SR#1157`. ``link_type.category`` is what every rule
about a relation reads, so that none of them is written in terms of a key a workspace may rename.

**The same three steps as ``491e1a09de04``, and for the same reason**: the column arrives
nullable, the five seeded keys are filled in, and only then does it become NOT NULL. Alembic's
autogenerated form adds it NOT NULL with no default, which fails on every database that has a
workspace in it — and every database has.

**An unrecognised key becomes ``describing``, which is the claim that asserts least.** It gates
nothing and refuses no ring. A migration cannot know what a relation somebody invented means, and
inferring ``ordering`` from a name like *precedes* would be the key deciding behaviour one last
time, in the place it is hardest to see. The consequence is written on `SR#1157` and is
deliberate: a workspace that has added its own ordering relation sets the category once, with
``PATCH /v1/link-types/{id}``.

**And the CHECK is written out because Alembic does not compare CHECK constraints.** The
vocabulary lives in one, so an ``enum_check`` that only ever reached the models would pass the
whole suite and never reach a migrated database.

Revision ID: da7628199bff
Revises: 491e1a09de04
Created: 2026-08-24 07:41:12.884213+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy


revision: str = 'da7628199bff'
down_revision: str | None = '491e1a09de04'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None

#: Decision `SR#1157`'s table. ``blocks`` is the only thing that holds work up; the two that
#: point at a written conclusion govern; the two that merely connect a pair describe.
CATEGORIES = {
    'blocks': 'gating',
    'documents': 'governing',
    'derives_from': 'governing',
    'relates_to': 'describing',
    'duplicates': 'describing',
}

#: What a key this migration does not recognise becomes. See the module docstring: the weakest
#: claim, so that nothing starts gating or refusing rings because of a name.
FALLBACK = 'describing'

VALUES = "'gating', 'ordering', 'governing', 'describing'"


def upgrade () -> None:
    """Give every link type a category, then hold the column to the vocabulary."""

    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column('category', sqlalchemy.String(length=16), nullable=True)
        )

    for key, category in CATEGORIES.items():
        op.execute(
            sqlalchemy.text(
                'UPDATE link_type SET category = :category WHERE key = :key'
            ).bindparams(category=category, key=key)
        )

    op.execute(
        sqlalchemy.text(
            'UPDATE link_type SET category = :category WHERE category IS NULL'
        ).bindparams(category=FALLBACK)
    )

    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.alter_column(
            'category', existing_type=sqlalchemy.String(length=16), nullable=False
        )
        batch_op.create_check_constraint('category', f'category IN ({VALUES})')


def downgrade () -> None:
    """Take it back out. Nothing else reads it, so nothing else has to move."""

    with op.batch_alter_table('link_type', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_link_type_category'), type_='check')
        batch_op.drop_column('category')
