"""task claims

Revision ID: e4862f5da622
Revises: 547fe53b263c
Created: 2026-08-03 11:16:35.124177+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'e4862f5da622'
down_revision: str | None = '547fe53b263c'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sqlalchemy.Column('claimed_by_id', sqlalchemy.Uuid(), nullable=True))
        batch_op.add_column(sqlalchemy.Column('claimed_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True))
        batch_op.add_column(sqlalchemy.Column('claim_expires_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_claimed_by_id'), ['claimed_by_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_claimed_by_id_user'), 'user', ['claimed_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_claimed_by_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_claimed_by_id'))
        batch_op.drop_column('claim_expires_at')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claimed_by_id')

    # ### end Alembic commands ###
