"""workspace slug frees on soft delete

Revision ID: ea3e86ad12c4
Revises: 2fee457e5b0b
Created: 2026-07-29 05:53:22.498582

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'ea3e86ad12c4'
down_revision: str | None = '2fee457e5b0b'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_workspace_slug'), type_='unique')
        batch_op.create_index('uq_workspace_slug', ['slug'], unique=True, sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # **The older schema cannot hold what this one allows.** Making the index partial is what
    # let a slug be reused once the workspace holding it was deleted, so an installation that
    # did so has two rows the plain constraint below cannot accept — and the downgrade died on
    # an integrity error naming a constraint rather than the data. Refused by name instead,
    # saying which slug and what to do about it.
    duplicates = op.get_bind().execute(
        sqlalchemy.text(
            "SELECT slug FROM workspace GROUP BY slug HAVING COUNT(*) > 1 ORDER BY slug"
        )
    ).scalars().all()

    if duplicates:
        raise RuntimeError(
            f"This installation has more than one workspace using each of "
            f"{', '.join(repr(slug) for slug in duplicates)} — which the schema before this "
            f"migration cannot represent, because it made every slug unique whether the "
            f"workspace was deleted or not. Purge the deleted ones, or rename them, and run "
            f"this again."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_index('uq_workspace_slug', sqlite_where=sqlalchemy.text('deleted_at IS NULL'), postgresql_where=sqlalchemy.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_workspace_slug'), ['slug'])

    # ### end Alembic commands ###
