"""A calendar feed is a credential in a URL

Revision ID: f159c8635e54
Revises: b6a0e7c14d92
Created: 2026-08-17 18:55:31.638223+00:00

One new table and nothing else, so there is no backfill and nothing to get wrong about
existing rows — `#916`, and docs/design.md §20.7 plus the item-type filter decision `#972` adds.

**The downgrade drops every feed, and that is not recoverable by re-upgrading.** A feed's
secret is stored as a hash, so a URL somebody has subscribed a calendar to cannot be
reconstructed: going back and forward again leaves the row gone and the client quietly
fetching a 404 for ever. Take a backup first, which ``subroutine db upgrade`` does anyway.

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import typing

from alembic import op

import sqlalchemy

import subroutine.db.types


revision: str = 'f159c8635e54'
down_revision: str | None = 'b6a0e7c14d92'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_feed',
    sqlalchemy.Column('id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('workspace_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('project_id', sqlalchemy.Uuid(), nullable=True),
    sqlalchemy.Column('owner_id', sqlalchemy.Uuid(), nullable=False),
    sqlalchemy.Column('audience', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('item_type_ids', sqlalchemy.JSON(), nullable=True),
    sqlalchemy.Column('title', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('token_prefix', sqlalchemy.String(length=32), nullable=False),
    sqlalchemy.Column('token_hash', sqlalchemy.String(length=128), nullable=False),
    sqlalchemy.Column('last_polled_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('expires_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('revoked_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=True),
    sqlalchemy.Column('created_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.Column('updated_at', subroutine.db.types.UtcDateTime(timezone=True), nullable=False),
    sqlalchemy.CheckConstraint("audience IN ('everything', 'assigned_to_me')", name=op.f('ck_calendar_feed_audience')),
    sqlalchemy.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_calendar_feed_owner_id_user'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_calendar_feed_project_id_project'), ondelete='CASCADE'),
    sqlalchemy.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_calendar_feed_workspace_id_workspace'), ondelete='CASCADE'),
    sqlalchemy.PrimaryKeyConstraint('id', name=op.f('pk_calendar_feed'))
    )
    with op.batch_alter_table('calendar_feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_feed_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_feed_token_prefix'), ['token_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_calendar_feed_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_feed_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_feed_token_prefix'))
        batch_op.drop_index(batch_op.f('ix_calendar_feed_owner_id'))

    op.drop_table('calendar_feed')
    # ### end Alembic commands ###
