"""An appointment and a deferred task are different things, and are named differently

``start_at`` carried two opposite intentions — *begins at* and *hide this until* — and every
consumer read it as the second. ``readiness.undeferred`` reads it to the minute, so
``Dentist on Monday at 2pm`` was filed under *Unscheduled*, hidden from ``--ready``, and
described as *"1 thing put off until later"*: invisible until the moment it stopped being
useful. Item ``#854``.

Three changes, in the order they have to happen:

- ``start_at`` becomes ``snoozed_until`` and ``start_is_all_day`` becomes
  ``snoozed_is_all_day``. **A pure rename — no row changes meaning.** Every existing row on
  every installation goes on behaving exactly as it did, which is the only honest backfill
  available: the column genuinely held both intentions and the data does not distinguish
  them. Anything that was really an appointment has to be re-filed by the person who knows.
- ``starts_at`` and ``starts_is_all_day`` are added, empty.
- ``planned_for`` is absorbed into ``starts_at`` and dropped. *Planned for Tuesday* is
  *starts Tuesday, all day*, and ``_apply_time`` already discarded the plan and wrote a
  start when handed both.

**The all-day flag survives onto the snooze deliberately.** ``#858`` — whether a defer
should honour a time of day or refuse one by name — is undecided, and dropping the flag
here would answer it by accident.

**The absorption resolves each date in the zone that stored it**, walking task → workspace
→ instance → UTC. Reading a day-scale date in the wrong zone moves it by a day for every
installation west of UTC, which is ``#773`` exactly, and a migration is the worst place to
meet it because there is nothing left to compare against afterwards.

**The downgrade is lossy and says so.** A timed ``starts_at`` — an appointment at two
o'clock — has nowhere to go in a ``planned_for`` that stores a date and nothing else, so
its time is dropped. All-day values round-trip exactly.

Revision ID: f2b8c1a94d63
Revises: a3f9c21d7e40
Created: 2026-08-15 00:00:00.000000+00:00

Generated by Alembic. Unlike the rest of the project this file is space-indented and
uses Alembic's own ``op`` convention rather than fully-qualified names: it is
machine-generated, and ``batch_alter_table`` emits ``op.`` regardless of configuration,
so a half-converted file would read worse than either convention applied consistently.
"""

import datetime
import typing
import zoneinfo

import sqlalchemy
from alembic import op

import subroutine.db.types


revision: str = 'f2b8c1a94d63'
down_revision: str | None = 'a3f9c21d7e40'
branch_labels: str | typing.Sequence[str] | None = None
depends_on: str | typing.Sequence[str] | None = None


#: Where ``schedule.zone_for``'s chain ends. The *user* step is unreachable from here and
#: correctly so: it resolves the caller's zone, and a stored task belongs to whoever filed
#: it rather than to whoever is migrating.
FALLBACK_TIMEZONE = 'UTC'


#: The task columns this migration reads and writes, **carrying their real types**.
#:
#: A value bound through a bare ``sqlalchemy.text()`` has no type information, so the driver
#: falls back to its own adapter — and on SQLite pysqlite renders a datetime as
#: ``2026-03-10 00:00:00+00:00`` where :class:`subroutine.db.types.UtcDateTime` renders
#: ``2026-03-10 00:00:00.000000``. Both read back as the same instant, so a migrated row looks
#: right everywhere a person would check it. But SQLite compares a DATETIME as *text*, and
#: ``+`` sorts before ``.``, so the migrated row falls outside the very range query its own
#: column exists to answer: a planned day absorbed by this migration was invisible to the
#: agenda while ``show`` displayed the correct date.
#:
#: Declared once and shared by both directions, so the read and the write cannot disagree
#: about a column's type — which would silently change what a workspace id compares equal to.
TASK = sqlalchemy.table(
    'task',
    sqlalchemy.column('id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('workspace_id', subroutine.db.types.uuid_column()),
    sqlalchemy.column('timezone', sqlalchemy.String()),
    sqlalchemy.column('planned_for', subroutine.db.types.CalendarDate()),
    sqlalchemy.column('starts_at', subroutine.db.types.UtcDateTime()),
    sqlalchemy.column('starts_is_all_day', sqlalchemy.Boolean()),
)


def _zone (named: str) -> datetime.tzinfo:
    """Return a named zone, falling back to UTC where this machine cannot name it.

    A zone the host has no database entry for must not stop an upgrade. The row still moves;
    it lands where it would have done had the column never carried a zone at all.
    """

    try:
        return zoneinfo.ZoneInfo(named)

    except (zoneinfo.ZoneInfoNotFoundError, ValueError):
        return datetime.UTC


def _zones (connection: sqlalchemy.Connection) -> dict[typing.Any, str]:
    """Return the timezone in force for each workspace, falling back to the instance's.

    Keyed through the same UUID type :data:`TASK` reads its ``workspace_id`` with. A raw
    ``text()`` select hands back a bare string on SQLite and a ``uuid.UUID`` on PostgreSQL,
    so a key read one way and looked up the other misses on exactly one backend.
    """

    instance = connection.execute(
        sqlalchemy.text('SELECT timezone FROM instance LIMIT 1')
    ).scalar()

    default = instance or FALLBACK_TIMEZONE

    workspaces = sqlalchemy.table(
        'workspace',
        sqlalchemy.column('id', subroutine.db.types.uuid_column()),
        sqlalchemy.column('timezone', sqlalchemy.String()),
    )

    rows = connection.execute(
        sqlalchemy.select(workspaces.c.id, workspaces.c.timezone)
    ).all()

    return {row[0]: row[1] or default for row in rows}


def _absorb_planned_days (connection: sqlalchemy.Connection) -> None:
    """Write each ``planned_for`` into ``starts_at`` as the start of that day, locally.

    Row by row rather than in one statement, because the zone differs per workspace and
    SQLite has no ``AT TIME ZONE``. It is bounded by how many tasks carry a planned day,
    which is a small number by construction — a planned day is what somebody intends to do
    *next*, not a property every task accumulates.
    """

    planned = connection.execute(
        sqlalchemy.select(
            TASK.c.id, TASK.c.workspace_id, TASK.c.timezone, TASK.c.planned_for
        ).where(TASK.c.planned_for.is_not(None))
    ).all()

    if not planned:
        return

    workspaces = _zones(connection)

    for identifier, workspace_id, stored, day in planned:
        named = stored or workspaces.get(workspace_id) or FALLBACK_TIMEZONE

        # A zone this machine cannot name must not stop an upgrade. The row still moves; it
        # lands on the same date in UTC, which is what it would have done had the column
        # never carried a zone at all.
        zone: datetime.tzinfo = _zone(named)

        local = datetime.datetime.combine(day, datetime.time.min, tzinfo=zone)

        connection.execute(
            sqlalchemy.update(TASK)
            .where(TASK.c.id == identifier)
            .values(starts_at=local.astimezone(datetime.UTC), starts_is_all_day=True)
        )


def _restore_planned_days (connection: sqlalchemy.Connection) -> None:
    """Write each ``starts_at`` back out as the calendar date it falls on, locally.

    **Lossy for a timed start**, which is stated in this migration's own summary: a two
    o'clock appointment becomes the day it happens on.
    """

    starting = connection.execute(
        sqlalchemy.select(
            TASK.c.id, TASK.c.workspace_id, TASK.c.timezone, TASK.c.starts_at
        ).where(TASK.c.starts_at.is_not(None))
    ).all()

    if not starting:
        return

    workspaces = _zones(connection)

    for identifier, workspace_id, stored, instant in starting:
        named = stored or workspaces.get(workspace_id) or FALLBACK_TIMEZONE

        zone: datetime.tzinfo = _zone(named)

        connection.execute(
            sqlalchemy.update(TASK)
            .where(TASK.c.id == identifier)
            .values(planned_for=instant.astimezone(zone).date())
        )


def upgrade () -> None:
    """Rename the defer, add the start, and absorb the planned day into it."""

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('start_at', new_column_name='snoozed_until')
        batch_op.alter_column(
            'start_is_all_day', new_column_name='snoozed_is_all_day'
        )
        batch_op.add_column(
            sqlalchemy.Column(
                'starts_at', subroutine.db.types.UtcDateTime(), nullable=True
            )
        )

        # **Added with a server default and then stripped of it.** The column is NOT NULL and
        # the table has rows, so there has to be a value for them; the model declares only a
        # Python-side default, so leaving one behind would show up as drift for ever.
        batch_op.add_column(
            sqlalchemy.Column(
                'starts_is_all_day',
                sqlalchemy.Boolean(),
                nullable=False,
                server_default=sqlalchemy.false(),
            )
        )

    _absorb_planned_days(op.get_bind())

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('starts_is_all_day', server_default=None)
        batch_op.drop_index(batch_op.f('ix_task_workspace_id_planned_for'))
        batch_op.create_index(
            batch_op.f('ix_task_workspace_id_starts_at'),
            ['workspace_id', 'starts_at'],
            unique=False,
        )
        batch_op.drop_column('planned_for')


def downgrade () -> None:
    """Put the planned day back, and give the defer its old name."""

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(
            sqlalchemy.Column(
                'planned_for', subroutine.db.types.CalendarDate(), nullable=True
            )
        )

    _restore_planned_days(op.get_bind())

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_workspace_id_starts_at'))
        batch_op.create_index(
            batch_op.f('ix_task_workspace_id_planned_for'),
            ['workspace_id', 'planned_for'],
            unique=False,
        )
        batch_op.drop_column('starts_is_all_day')
        batch_op.drop_column('starts_at')
        batch_op.alter_column(
            'snoozed_is_all_day', new_column_name='start_is_all_day'
        )
        batch_op.alter_column('snoozed_until', new_column_name='start_at')
